// Auto-generated by scrape_market.py from guiafantasy.com
// Generated: 2026-01-09 00:06
// Total Players: 385
const MARKET_DATA = {
  "Pedri": 164936047,
  "Remiro": 5974456,
  "Iñaki Williams": 9640326,
  "David Soria": 8637026,
  "Berenguer": 26410407,
  "Raíllo": 7115942,
  "Sergio Herrera": 14961133,
  "Sergio Gómez": 5397027,
  "Courtois": 48005837,
  "Lejeune": 38989896,
  "Kubo": 24621471,
  "Pau Cubarsí": 38726829,
  "Rubén García": 8262281,
  "Darder": 10629706,
  "Diego López": 4162667,
  "Álvaro García": 18020941,
  "Rioja": 10208827,
  "Arambarri": 19959938,
  "Marcos Llorente": 74124544,
  "De Frutos": 26587468,
  "Kumbulla": 586648,
  "Marcos Alonso": 22378018,
  "Cardona": 8974205,
  "Álex Balde": 45131829,
  "Giuliano": 57119594,
  "Boyomo": 8501566,
  "Tchouaméni": 56950365,
  "Valjent": 3303078,
  "Tárrega": 6552598,
  "Carmona": 7400292,
  "Jofre": 577783,
  "Comesaña": 36049006,
  "Catena": 56770209,
  "Guruzeta": 1473350,
  "Parejo": 816788,
  "Barrios": 65282450,
  "Sow": 615260,
  "Juan Iglesias": 1004994,
  "Jauregizar": 31061872,
  "Torró": 828207,
  "Hansi Flick": 644484,
  "Arnau": 1291937,
  "Yuri": 10677052,
  "Daley Blind": 1136876,
  "Iván Martín": 2362669,
  "Samu Costa": 1931324,
  "Fran Beltrán": 592981,
  "Pedrosa": 578098,
  "David López": 599423,
  "Javi Rodríguez": 597003,
  "Almeida": 913436,
  "De Galarreta": 8051189,
  "Abel Bretones": 918476,
  "Hugo Duro": 4984449,
  "Chavarría": 17888623,
  "Juanlu": 800296,
  "Bartra": 35941200,
  "Altimira": 1528376,
  "Tsygankov": 5304994,
  "Blanco": 2938293,
  "Conor Gallagher": 1082649,
  "Agirrezabala": 7900161,
  "Sivera": 3895024,
  "Tenaglia": 15603840,
  "Ernesto Valverde": 592144,
  "Zubeldia": 3429468,
  "Guridi": 595812,
  "Guevara": 582308,
  "Óscar Valentín": 942678,
  "Prados": 579791,
  "El Hilali": 2648812,
  "Arda Güler": 80101378,
  "Le Normand": 12189057,
  "Barrenetxea": 40286708,
  "Hugo Alvarez": 674066,
  "Fornals": 110116219,
  "Moncayola": 5947089,
  "Marcelino": 593865,
  "Asencio": 7414810,
  "Morlanes": 606181,
  "Gerard": 41044646,
  "Asprilla": 669948,
  "Gayá": 1509835,
  "Jagoba Arrasate": 584538,
  "Unai Simón": 13642715,
  "Claudio Giraldez": 582681,
  "Domingos Duarte": 1573479,
  "Camavinga": 19487885,
  "Fermín": 125110243,
  "Iñigo Perez": 582345,
  "Mouriño": 9817553,
  "José Bordalás": 578412,
  "Vesga": 578047,
  "Pol Lozano": 730075,
  "Moi Gómez": 1001658,
  "Turrientes": 585678,
  "Moussa Diarra": 575331,
  "Gavi": 842870,
  "Balliu": 583011,
  "Cucho": 106499322,
  "Francés": 577255,
  "Portu": 580068,
  "Iker Muñoz": 576532,
  "Iván Villar": 575975,
  "Edu Expósito": 71902331,
  "F. Garcés": 692702,
  "Ramón Martínez": 572696,
  "Aitor Fdez": 576861,
  "Yoel Lago": 573707,
  "Aarón": 27758848,
  "Ez Abde": 34905024,
  "A. Rebbach": 575630,
  "A. Abqar": 937627,
  "Abdón": 576632,
  "A. Mumin": 575385,
  "Abel Ruiz": 578412,
  "Kamara": 604853,
  "Adam B.": 574390,
  "Adama": 574390,
  "Januzaj": 590081,
  "A. Alti": 581382,
  "Dela": 575959,
  "A. Liso": 2832674,
  "Adrián Molina": 572865,
  "Adrián": 571357,
  "Aihen": 582026,
  "Aimar Blázquez": 573156,
  "Aimar": 5537051,
  "Fraga": 572363,
  "Mañas": 479639,
  "Paredes": 8500580,
  "Aitor Ruibal": 1024164,
  "Akor": 829911,
  "Alan Matturro": 585400,
  "Alassane": 408007,
  "Albert": 574418,
  "Alberto F.": 573560,
  "A. Moleiro": 107830587,
  "A. Reina": 584724,
  "Risco": 573460,
  "Febas": 11878547,
  "A. Iturbe": 573804,
  "Panach": 552025,
  "Rego": 575360,
  "Álex Sancris": 587649,
  "Puri?": 612606,
  "Andreev": 574286,
  "Alessio Lisci": 581584,
  "Álex Baena": 60001127,
  "Alex Costa": 573803,
  "A. Fores": 573831,
  "Lebarbier": 570927,
  "Alex Marchal": 562615,
  "Alex Moreno": 845862,
  "Padilla": 578982,
  "A. Primo": 583012,
  "Sørloth": 6006832,
  "Alemâo": 645216,
  "Alexis Sánchez": 2329318,
  "Alfon": 734980,
  "Pacha": 578785,
  "A. Pedraza": 1380787,
  "A. Houary": 577277,
  "Nyom": 573123,
  "Á. Carreras": 75603497,
  "A. Ferllo": 580820,
  "Álvaro Nuñez": 24023965,
  "Odriozola": 577874,
  "Álvaro": 2893966,
  "Á. Valles": 3289916,
  "Gorosabel": 596359,
  "André Silva": 4016926,
  "Christensen": 755511,
  "Ratiu": 46050802,
  "A. Castrín": 593294,
  "Lunin": 586828,
  "A. Arcos": 479639,
  "A. Fortuño": 575102,
  "Á. Ortiz": 581676,
  "Budimir": 18133614,
  "Griezmann": 25090906,
  "Toni Lato": 575042,
  "A. Martinez": 573123,
  "Rüdiger": 21472505,
  "Salguero": 558069,
  "Antonio Sánchez": 577263,
  "A. Roca": 572803,
  "Antony": 107509366,
  "Aritz": 578842,
  "Mariezkurrena": 613043,
  "Arnau Tenas": 624106,
  "Danjuma": 14797407,
  "Zakharyan": 583208,
  "Asier Hierro": 535685,
  "A. Osambela": 572442,
  "A. Batalla": 13603630,
  "Witsel": 3079272,
  "Laporte": 12803435,
  "Ayoze": 25386134,
  "Ounahi": 7918057,
  "Diaby": 574109,
  "Santamaría": 783811,
  "Mendy": 1106854,
  "B. Iglesias": 16805648,
  "B. Mayoral": 4137272,
  "Brahim": 2038431,
  "Brais Méndez": 26512428,
  "Bryan Gil": 1589229,
  "Bryan": 3648214,
  "Calebe": 577260,
  "Starfelt": 2661533,
  "Aleñá": 3389681,
  "C. Alvarez": 6424153,
  "Ballestero": 572822,
  "Protesoni": 579766,
  "Carlos Corberán": 574793,
  "C. Dominguez": 576944,
  "C. Espí": 574723,
  "Carlos Macià": 679685,
  "Carlos Martín": 575051,
  "C. Romero": 41182824,
  "C. Soler": 9820948,
  "Carlos V.": 9393664,
  "Cayetano": 572827,
  "Bakambu": 589746,
  "Azpilicueta": 916033,
  "Pickel": 584201,
  "Ejuke": 676166,
  "Chimy Ávila": 584654,
  "Riedel": 1018747,
  "Lenglet": 1170699,
  "Coba": 573064,
  "Stuani": 588767,
  "C. Rivero": 573873,
  "Damian": 576453,
  "Dani Calvo": 591685,
  "D. Cárdenas": 573847,
  "Carvajal": 3518297,
  "D. Ceballos": 713204,
  "D. Martínez": 479639,
  "Dani Olmo": 33164216,
  "Raba": 829092,
  "Vivian": 17300199,
  "D. Pérez": 573792,
  "Bladi": 574390,
  "Affengruber": 19781782,
  "Alaba": 597449,
  "Davinchi": 593955,
  "David Costas": 710156,
  "David Delgado": 572363,
  "Hancko": 29363937,
  "D. Jiménez": 574323,
  "David Carmo": 1136018,
  "Otorbi": 573460,
  "Huijsen": 54714186,
  "Denis Suárez": 601136,
  "Diego Aguado": 574250,
  "Diego Conde": 591675,
  "Ferrer": 574286,
  "Kochen": 573470,
  "Llorente": 611255,
  "Dieguito": 408007,
  "Morcillo": 574286,
  "Pampin": 573777,
  "Rico": 1310735,
  "Simeone": 598827,
  "Foulquier": 794798,
  "Stamatakis": 572760,
  "Djene": 4054835,
  "Livakovic": 747454,
  "Van De Beek": 580927,
  "Dro": 578629,
  "Caleta-Car": 788444,
  "Eder Aller": 575749,
  "E. Militão": 34866034,
  "Eder García": 535685,
  "Eder Sarabia": 576395,
  "Edu Altozano": 573290,
  "Coudet": 586976,
  "Egoitz M.l.": 558069,
  "Bujan": 535685,
  "Cömert": 577084,
  "E. Bailly": 582794,
  "Eric": 65809355,
  "Cardoso": 598900,
  "Redondo": 588138,
  "Valverde": 77011956,
  "F. Viñas": 614322,
  "Félix": 577216,
  "F. Mendy": 599173,
  "F. Calero": 2555719,
  "Ferri": 467610,
  "Ferran Jutglà": 1214770,
  "Ferran": 110006903,
  "Ugrinic": 600481,
  "Fran García": 671506,
  "Fran González": 573294,
  "Fran Pérez": 619405,
  "Isco": 23101093,
  "Franco Cervi": 575685,
  "F. Mastantuono": 6773302,
  "F. De Jong": 51736231,
  "Suazo": 2732579,
  "Mikautadze": 12870488,
  "Peque": 584766,
  "Gumbau": 579344,
  "Gerard Martín": 19167722,
  "Germán": 574400,
  "German V.": 40012203,
  "Raspadori": 665484,
  "Gibi": 572755,
  "Lo Celso": 23750352,
  "Koyalipou": 591573,
  "Guedes": 19523390,
  "Gonzalo": 1507856,
  "Gorka Carrera": 605859,
  "Grady Diangana": 609788,
  "Swiderski": 572755,
  "Guille Fernández": 573493,
  "Guillermo Almada": 819080,
  "Hassan": 1018910,
  "Bellerín": 11837424,
  "Héctor Fort": 1173301,
  "Moldovan": 577320,
  "H. González": 558069,
  "Hugo Lopez": 572718,
  "H. Rincón": 577216,
  "Solozabal": 503679,
  "Hugo Sotelo": 1976009,
  "Huseini": 558069,
  "Iago Aspas": 4415895,
  "Aguirre": 408007,
  "Ibon Sánchez": 571357,
  "I. Benito": 575528,
  "Iker Losada": 579396,
  "Monreal": 572822,
  "I. Akhomach": 581810,
  "Kostis": 573540,
  "Salhi": 573175,
  "Ilyas": 609170,
  "Iñaki Peña": 2349174,
  "Arguibide": 566028,
  "I. Lekue": 583435,
  "Ionut Radu": 11272524,
  "Isaac": 1829389,
  "Isi": 9028918,
  "Ismael": 577317,
  "Sierra": 572363,
  "Iván": 573290,
  "Cuéllar": 574614,
  "I. Romero": 3107206,
  "Izei": 479639,
  "Oblak": 22662877,
  "Jan Virgili": 10283069,
  "Jandro": 408007,
  "Jano": 572865,
  "Javi Galán": 875526,
  "Javi Guerra": 4268288,
  "Javi H.": 575023,
  "Javi Llabrés": 574284,
  "Javi López": 578276,
  "Javi Muñoz": 586948,
  "Puado": 5380554,
  "Javi Rueda": 3854071,
  "Javi Serrano": 575658,
  "J. Boñar": 546123,
  "Javi Navarro": 572363,
  "Olaizola": 572363,
  "Sarasa": 575749,
  "J. Ives Valou": 572827,
  "Jeremy Toljan": 902933,
  "Areso": 4430269,
  "Fortea": 574006,
  "J. Vázquez": 618835,
  "Jhon Solis": 573682,
  "Letacek": 574273,
  "Joan García": 64774418,
  "Jordán": 579182,
  "Joan Martínez": 642453,
  "Joan Ruiz": 573730,
  "Oso": 587106,
  "Fontanet": 408007,
  "Joel Roca": 604044,
  "J. Mojica": 10355018,
  "John C.": 575390
};
const MARKET_INFO = {
  "Pedri": {
    "position": "MD",
    "points": 198,
    "value": 164936047
  },
  "Remiro": {
    "position": "PT",
    "points": 181,
    "value": 5974456
  },
  "Iñaki Williams": {
    "position": "DL",
    "points": 178,
    "value": 9640326
  },
  "David Soria": {
    "position": "PT",
    "points": 176,
    "value": 8637026
  },
  "Berenguer": {
    "position": "DL",
    "points": 172,
    "value": 26410407
  },
  "Raíllo": {
    "position": "DF",
    "points": 164,
    "value": 7115942
  },
  "Sergio Herrera": {
    "position": "PT",
    "points": 161,
    "value": 14961133
  },
  "Sergio Gómez": {
    "position": "DF",
    "points": 160,
    "value": 5397027
  },
  "Courtois": {
    "position": "PT",
    "points": 157,
    "value": 48005837
  },
  "Lejeune": {
    "position": "DF",
    "points": 149,
    "value": 38989896
  },
  "Kubo": {
    "position": "MD",
    "points": 147,
    "value": 24621471
  },
  "Pau Cubarsí": {
    "position": "DF",
    "points": 142,
    "value": 38726829
  },
  "Rubén García": {
    "position": "MD",
    "points": 142,
    "value": 8262281
  },
  "Darder": {
    "position": "MD",
    "points": 141,
    "value": 10629706
  },
  "Diego López": {
    "position": "DL",
    "points": 139,
    "value": 4162667
  },
  "Álvaro García": {
    "position": "MD",
    "points": 135,
    "value": 18020941
  },
  "Rioja": {
    "position": "MD",
    "points": 135,
    "value": 10208827
  },
  "Arambarri": {
    "position": "MD",
    "points": 133,
    "value": 19959938
  },
  "Marcos Llorente": {
    "position": "DF",
    "points": 130,
    "value": 74124544
  },
  "De Frutos": {
    "position": "DL",
    "points": 129,
    "value": 26587468
  },
  "Kumbulla": {
    "position": "DF",
    "points": 127,
    "value": 586648
  },
  "Marcos Alonso": {
    "position": "DF",
    "points": 125,
    "value": 22378018
  },
  "Cardona": {
    "position": "DF",
    "points": 124,
    "value": 8974205
  },
  "Álex Balde": {
    "position": "DF",
    "points": 121,
    "value": 45131829
  },
  "Giuliano": {
    "position": "DL",
    "points": 121,
    "value": 57119594
  },
  "Boyomo": {
    "position": "DF",
    "points": 120,
    "value": 8501566
  },
  "Tchouaméni": {
    "position": "MD",
    "points": 119,
    "value": 56950365
  },
  "Valjent": {
    "position": "DF",
    "points": 115,
    "value": 3303078
  },
  "Tárrega": {
    "position": "DF",
    "points": 114,
    "value": 6552598
  },
  "Carmona": {
    "position": "DF",
    "points": 114,
    "value": 7400292
  },
  "Jofre": {
    "position": "DL",
    "points": 113,
    "value": 577783
  },
  "Comesaña": {
    "position": "MD",
    "points": 111,
    "value": 36049006
  },
  "Catena": {
    "position": "DF",
    "points": 110,
    "value": 56770209
  },
  "Guruzeta": {
    "position": "DL",
    "points": 109,
    "value": 1473350
  },
  "Parejo": {
    "position": "MD",
    "points": 106,
    "value": 816788
  },
  "Barrios": {
    "position": "MD",
    "points": 106,
    "value": 65282450
  },
  "Sow": {
    "position": "MD",
    "points": 105,
    "value": 615260
  },
  "Juan Iglesias": {
    "position": "DF",
    "points": 105,
    "value": 1004994
  },
  "Jauregizar": {
    "position": "MD",
    "points": 105,
    "value": 31061872
  },
  "Torró": {
    "position": "MD",
    "points": 103,
    "value": 828207
  },
  "Hansi Flick": {
    "position": "UNK",
    "points": 101,
    "value": 644484
  },
  "Arnau": {
    "position": "DF",
    "points": 100,
    "value": 1291937
  },
  "Yuri": {
    "position": "DF",
    "points": 100,
    "value": 10677052
  },
  "Daley Blind": {
    "position": "DF",
    "points": 99,
    "value": 1136876
  },
  "Iván Martín": {
    "position": "MD",
    "points": 98,
    "value": 2362669
  },
  "Samu Costa": {
    "position": "MD",
    "points": 97,
    "value": 1931324
  },
  "Fran Beltrán": {
    "position": "MD",
    "points": 96,
    "value": 592981
  },
  "Pedrosa": {
    "position": "DF",
    "points": 95,
    "value": 578098
  },
  "David López": {
    "position": "DF",
    "points": 95,
    "value": 599423
  },
  "Javi Rodríguez": {
    "position": "DF",
    "points": 95,
    "value": 597003
  },
  "Almeida": {
    "position": "MD",
    "points": 94,
    "value": 913436
  },
  "De Galarreta": {
    "position": "MD",
    "points": 94,
    "value": 8051189
  },
  "Abel Bretones": {
    "position": "DF",
    "points": 93,
    "value": 918476
  },
  "Hugo Duro": {
    "position": "DL",
    "points": 93,
    "value": 4984449
  },
  "Chavarría": {
    "position": "DF",
    "points": 93,
    "value": 17888623
  },
  "Juanlu": {
    "position": "MD",
    "points": 93,
    "value": 800296
  },
  "Bartra": {
    "position": "DF",
    "points": 93,
    "value": 35941200
  },
  "Altimira": {
    "position": "MD",
    "points": 93,
    "value": 1528376
  },
  "Tsygankov": {
    "position": "DL",
    "points": 93,
    "value": 5304994
  },
  "Blanco": {
    "position": "MD",
    "points": 92,
    "value": 2938293
  },
  "Conor Gallagher": {
    "position": "MD",
    "points": 92,
    "value": 1082649
  },
  "Agirrezabala": {
    "position": "PT",
    "points": 92,
    "value": 7900161
  },
  "Sivera": {
    "position": "PT",
    "points": 90,
    "value": 3895024
  },
  "Tenaglia": {
    "position": "DF",
    "points": 89,
    "value": 15603840
  },
  "Ernesto Valverde": {
    "position": "UNK",
    "points": 88,
    "value": 592144
  },
  "Zubeldia": {
    "position": "DF",
    "points": 88,
    "value": 3429468
  },
  "Guridi": {
    "position": "MD",
    "points": 88,
    "value": 595812
  },
  "Guevara": {
    "position": "MD",
    "points": 85,
    "value": 582308
  },
  "Óscar Valentín": {
    "position": "MD",
    "points": 85,
    "value": 942678
  },
  "Prados": {
    "position": "MD",
    "points": 84,
    "value": 579791
  },
  "El Hilali": {
    "position": "DF",
    "points": 84,
    "value": 2648812
  },
  "Arda Güler": {
    "position": "MD",
    "points": 83,
    "value": 80101378
  },
  "Le Normand": {
    "position": "DF",
    "points": 83,
    "value": 12189057
  },
  "Barrenetxea": {
    "position": "MD",
    "points": 80,
    "value": 40286708
  },
  "Hugo Alvarez": {
    "position": "MD",
    "points": 80,
    "value": 674066
  },
  "Fornals": {
    "position": "MD",
    "points": 80,
    "value": 110116219
  },
  "Moncayola": {
    "position": "MD",
    "points": 78,
    "value": 5947089
  },
  "Marcelino": {
    "position": "UNK",
    "points": 76,
    "value": 593865
  },
  "Asencio": {
    "position": "DF",
    "points": 73,
    "value": 7414810
  },
  "Morlanes": {
    "position": "MD",
    "points": 72,
    "value": 606181
  },
  "Gerard": {
    "position": "DL",
    "points": 71,
    "value": 41044646
  },
  "Asprilla": {
    "position": "DL",
    "points": 71,
    "value": 669948
  },
  "Gayá": {
    "position": "DF",
    "points": 70,
    "value": 1509835
  },
  "Jagoba Arrasate": {
    "position": "UNK",
    "points": 69,
    "value": 584538
  },
  "Unai Simón": {
    "position": "PT",
    "points": 69,
    "value": 13642715
  },
  "Claudio Giraldez": {
    "position": "UNK",
    "points": 67,
    "value": 582681
  },
  "Domingos Duarte": {
    "position": "DF",
    "points": 66,
    "value": 1573479
  },
  "Camavinga": {
    "position": "MD",
    "points": 66,
    "value": 19487885
  },
  "Fermín": {
    "position": "MD",
    "points": 65,
    "value": 125110243
  },
  "Iñigo Perez": {
    "position": "UNK",
    "points": 65,
    "value": 582345
  },
  "Mouriño": {
    "position": "DF",
    "points": 65,
    "value": 9817553
  },
  "José Bordalás": {
    "position": "UNK",
    "points": 61,
    "value": 578412
  },
  "Vesga": {
    "position": "MD",
    "points": 55,
    "value": 578047
  },
  "Pol Lozano": {
    "position": "MD",
    "points": 53,
    "value": 730075
  },
  "Moi Gómez": {
    "position": "MD",
    "points": 48,
    "value": 1001658
  },
  "Turrientes": {
    "position": "MD",
    "points": 47,
    "value": 585678
  },
  "Moussa Diarra": {
    "position": "DF",
    "points": 42,
    "value": 575331
  },
  "Gavi": {
    "position": "MD",
    "points": 36,
    "value": 842870
  },
  "Balliu": {
    "position": "DF",
    "points": 35,
    "value": 583011
  },
  "Cucho": {
    "position": "DL",
    "points": 33,
    "value": 106499322
  },
  "Francés": {
    "position": "DF",
    "points": 32,
    "value": 577255
  },
  "Portu": {
    "position": "DL",
    "points": 29,
    "value": 580068
  },
  "Iker Muñoz": {
    "position": "MD",
    "points": 24,
    "value": 576532
  },
  "Iván Villar": {
    "position": "PT",
    "points": 22,
    "value": 575975
  },
  "Edu Expósito": {
    "position": "MD",
    "points": 11,
    "value": 71902331
  },
  "F. Garcés": {
    "position": "DF",
    "points": 2,
    "value": 692702
  },
  "Ramón Martínez": {
    "position": "DF",
    "points": 2,
    "value": 572696
  },
  "Aitor Fdez": {
    "position": "PT",
    "points": 0,
    "value": 576861
  },
  "Yoel Lago": {
    "position": "DF",
    "points": 0,
    "value": 573707
  },
  "Aarón": {
    "position": "PT",
    "points": 0,
    "value": 27758848
  },
  "Ez Abde": {
    "position": "DL",
    "points": 0,
    "value": 34905024
  },
  "A. Rebbach": {
    "position": "DL",
    "points": 0,
    "value": 575630
  },
  "A. Abqar": {
    "position": "DF",
    "points": 0,
    "value": 937627
  },
  "Abdón": {
    "position": "DL",
    "points": 0,
    "value": 576632
  },
  "A. Mumin": {
    "position": "DF",
    "points": 0,
    "value": 575385
  },
  "Abel Ruiz": {
    "position": "DL",
    "points": 0,
    "value": 578412
  },
  "Kamara": {
    "position": "DL",
    "points": 0,
    "value": 604853
  },
  "Adam B.": {
    "position": "MD",
    "points": 0,
    "value": 574390
  },
  "Adama": {
    "position": "DF",
    "points": 0,
    "value": 574390
  },
  "Januzaj": {
    "position": "MD",
    "points": 0,
    "value": 590081
  },
  "A. Alti": {
    "position": "DF",
    "points": 0,
    "value": 581382
  },
  "Dela": {
    "position": "DF",
    "points": 0,
    "value": 575959
  },
  "A. Liso": {
    "position": "DL",
    "points": 0,
    "value": 2832674
  },
  "Adrián Molina": {
    "position": "PT",
    "points": 0,
    "value": 572865
  },
  "Adrián": {
    "position": "DL",
    "points": 0,
    "value": 571357
  },
  "Aihen": {
    "position": "DF",
    "points": 0,
    "value": 582026
  },
  "Aimar Blázquez": {
    "position": "DL",
    "points": 0,
    "value": 573156
  },
  "Aimar": {
    "position": "MD",
    "points": 0,
    "value": 5537051
  },
  "Fraga": {
    "position": "PT",
    "points": 0,
    "value": 572363
  },
  "Mañas": {
    "position": "DL",
    "points": 0,
    "value": 479639
  },
  "Paredes": {
    "position": "DF",
    "points": 0,
    "value": 8500580
  },
  "Aitor Ruibal": {
    "position": "DL",
    "points": 0,
    "value": 1024164
  },
  "Akor": {
    "position": "DL",
    "points": 0,
    "value": 829911
  },
  "Alan Matturro": {
    "position": "DF",
    "points": 0,
    "value": 585400
  },
  "Alassane": {
    "position": "MD",
    "points": 0,
    "value": 408007
  },
  "Albert": {
    "position": "DF",
    "points": 0,
    "value": 574418
  },
  "Alberto F.": {
    "position": "PT",
    "points": 0,
    "value": 573560
  },
  "A. Moleiro": {
    "position": "MD",
    "points": 0,
    "value": 107830587
  },
  "A. Reina": {
    "position": "MD",
    "points": 0,
    "value": 584724
  },
  "Risco": {
    "position": "MD",
    "points": 0,
    "value": 573460
  },
  "Febas": {
    "position": "MD",
    "points": 0,
    "value": 11878547
  },
  "A. Iturbe": {
    "position": "PT",
    "points": 0,
    "value": 573804
  },
  "Panach": {
    "position": "DF",
    "points": 0,
    "value": 552025
  },
  "Rego": {
    "position": "DF",
    "points": 0,
    "value": 575360
  },
  "Álex Sancris": {
    "position": "DL",
    "points": 0,
    "value": 587649
  },
  "Puri?": {
    "position": "DF",
    "points": 0,
    "value": 612606
  },
  "Andreev": {
    "position": "PT",
    "points": 0,
    "value": 574286
  },
  "Alessio Lisci": {
    "position": "UNK",
    "points": 0,
    "value": 581584
  },
  "Álex Baena": {
    "position": "MD",
    "points": 0,
    "value": 60001127
  },
  "Alex Costa": {
    "position": "DL",
    "points": 0,
    "value": 573803
  },
  "A. Fores": {
    "position": "DL",
    "points": 0,
    "value": 573831
  },
  "Lebarbier": {
    "position": "DF",
    "points": 0,
    "value": 570927
  },
  "Alex Marchal": {
    "position": "MD",
    "points": 0,
    "value": 562615
  },
  "Alex Moreno": {
    "position": "DF",
    "points": 0,
    "value": 845862
  },
  "Padilla": {
    "position": "PT",
    "points": 0,
    "value": 578982
  },
  "A. Primo": {
    "position": "PT",
    "points": 0,
    "value": 583012
  },
  "Sørloth": {
    "position": "DL",
    "points": 0,
    "value": 6006832
  },
  "Alemâo": {
    "position": "DL",
    "points": 0,
    "value": 645216
  },
  "Alexis Sánchez": {
    "position": "DL",
    "points": 0,
    "value": 2329318
  },
  "Alfon": {
    "position": "DL",
    "points": 0,
    "value": 734980
  },
  "Pacha": {
    "position": "DF",
    "points": 0,
    "value": 578785
  },
  "A. Pedraza": {
    "position": "DF",
    "points": 0,
    "value": 1380787
  },
  "A. Houary": {
    "position": "DL",
    "points": 0,
    "value": 577277
  },
  "Nyom": {
    "position": "DF",
    "points": 0,
    "value": 573123
  },
  "Á. Carreras": {
    "position": "DF",
    "points": 0,
    "value": 75603497
  },
  "A. Ferllo": {
    "position": "PT",
    "points": 0,
    "value": 580820
  },
  "Álvaro Nuñez": {
    "position": "DF",
    "points": 0,
    "value": 24023965
  },
  "Odriozola": {
    "position": "DF",
    "points": 0,
    "value": 577874
  },
  "Álvaro": {
    "position": "DL",
    "points": 0,
    "value": 2893966
  },
  "Á. Valles": {
    "position": "PT",
    "points": 0,
    "value": 3289916
  },
  "Gorosabel": {
    "position": "DF",
    "points": 0,
    "value": 596359
  },
  "André Silva": {
    "position": "DL",
    "points": 0,
    "value": 4016926
  },
  "Christensen": {
    "position": "DF",
    "points": 0,
    "value": 755511
  },
  "Ratiu": {
    "position": "DF",
    "points": 0,
    "value": 46050802
  },
  "A. Castrín": {
    "position": "DF",
    "points": 0,
    "value": 593294
  },
  "Lunin": {
    "position": "PT",
    "points": 0,
    "value": 586828
  },
  "A. Arcos": {
    "position": "MD",
    "points": 0,
    "value": 479639
  },
  "A. Fortuño": {
    "position": "PT",
    "points": 0,
    "value": 575102
  },
  "Á. Ortiz": {
    "position": "DF",
    "points": 0,
    "value": 581676
  },
  "Budimir": {
    "position": "DL",
    "points": 0,
    "value": 18133614
  },
  "Griezmann": {
    "position": "DL",
    "points": 0,
    "value": 25090906
  },
  "Toni Lato": {
    "position": "DF",
    "points": 0,
    "value": 575042
  },
  "A. Martinez": {
    "position": "MD",
    "points": 0,
    "value": 573123
  },
  "Rüdiger": {
    "position": "DF",
    "points": 0,
    "value": 21472505
  },
  "Salguero": {
    "position": "DF",
    "points": 0,
    "value": 558069
  },
  "Antonio Sánchez": {
    "position": "MD",
    "points": 0,
    "value": 577263
  },
  "A. Roca": {
    "position": "MD",
    "points": 0,
    "value": 572803
  },
  "Antony": {
    "position": "DL",
    "points": 0,
    "value": 107509366
  },
  "Aritz": {
    "position": "DF",
    "points": 0,
    "value": 578842
  },
  "Mariezkurrena": {
    "position": "DL",
    "points": 0,
    "value": 613043
  },
  "Arnau Tenas": {
    "position": "PT",
    "points": 0,
    "value": 624106
  },
  "Danjuma": {
    "position": "DL",
    "points": 0,
    "value": 14797407
  },
  "Zakharyan": {
    "position": "MD",
    "points": 0,
    "value": 583208
  },
  "Asier Hierro": {
    "position": "DL",
    "points": 0,
    "value": 535685
  },
  "A. Osambela": {
    "position": "MD",
    "points": 0,
    "value": 572442
  },
  "A. Batalla": {
    "position": "PT",
    "points": 0,
    "value": 13603630
  },
  "Witsel": {
    "position": "MD",
    "points": 0,
    "value": 3079272
  },
  "Laporte": {
    "position": "DF",
    "points": 0,
    "value": 12803435
  },
  "Ayoze": {
    "position": "DL",
    "points": 0,
    "value": 25386134
  },
  "Ounahi": {
    "position": "MD",
    "points": 0,
    "value": 7918057
  },
  "Diaby": {
    "position": "DF",
    "points": 0,
    "value": 574109
  },
  "Santamaría": {
    "position": "MD",
    "points": 0,
    "value": 783811
  },
  "Mendy": {
    "position": "MD",
    "points": 0,
    "value": 1106854
  },
  "B. Iglesias": {
    "position": "DL",
    "points": 0,
    "value": 16805648
  },
  "B. Mayoral": {
    "position": "DL",
    "points": 0,
    "value": 4137272
  },
  "Brahim": {
    "position": "MD",
    "points": 0,
    "value": 2038431
  },
  "Brais Méndez": {
    "position": "MD",
    "points": 0,
    "value": 26512428
  },
  "Bryan Gil": {
    "position": "DL",
    "points": 0,
    "value": 1589229
  },
  "Bryan": {
    "position": "DL",
    "points": 0,
    "value": 3648214
  },
  "Calebe": {
    "position": "MD",
    "points": 0,
    "value": 577260
  },
  "Starfelt": {
    "position": "DF",
    "points": 0,
    "value": 2661533
  },
  "Aleñá": {
    "position": "MD",
    "points": 0,
    "value": 3389681
  },
  "C. Alvarez": {
    "position": "MD",
    "points": 0,
    "value": 6424153
  },
  "Ballestero": {
    "position": "DF",
    "points": 0,
    "value": 572822
  },
  "Protesoni": {
    "position": "MD",
    "points": 0,
    "value": 579766
  },
  "Carlos Corberán": {
    "position": "UNK",
    "points": 0,
    "value": 574793
  },
  "C. Dominguez": {
    "position": "DF",
    "points": 0,
    "value": 576944
  },
  "C. Espí": {
    "position": "DL",
    "points": 0,
    "value": 574723
  },
  "Carlos Macià": {
    "position": "MD",
    "points": 0,
    "value": 679685
  },
  "Carlos Martín": {
    "position": "MD",
    "points": 0,
    "value": 575051
  },
  "C. Romero": {
    "position": "DF",
    "points": 0,
    "value": 41182824
  },
  "C. Soler": {
    "position": "MD",
    "points": 0,
    "value": 9820948
  },
  "Carlos V.": {
    "position": "DL",
    "points": 0,
    "value": 9393664
  },
  "Cayetano": {
    "position": "PT",
    "points": 0,
    "value": 572827
  },
  "Bakambu": {
    "position": "DL",
    "points": 0,
    "value": 589746
  },
  "Azpilicueta": {
    "position": "DF",
    "points": 0,
    "value": 916033
  },
  "Pickel": {
    "position": "MD",
    "points": 0,
    "value": 584201
  },
  "Ejuke": {
    "position": "DL",
    "points": 0,
    "value": 676166
  },
  "Chimy Ávila": {
    "position": "DL",
    "points": 0,
    "value": 584654
  },
  "Riedel": {
    "position": "DF",
    "points": 0,
    "value": 1018747
  },
  "Lenglet": {
    "position": "DF",
    "points": 0,
    "value": 1170699
  },
  "Coba": {
    "position": "MD",
    "points": 0,
    "value": 573064
  },
  "Stuani": {
    "position": "DL",
    "points": 0,
    "value": 588767
  },
  "C. Rivero": {
    "position": "PT",
    "points": 0,
    "value": 573873
  },
  "Damian": {
    "position": "MD",
    "points": 0,
    "value": 576453
  },
  "Dani Calvo": {
    "position": "DF",
    "points": 0,
    "value": 591685
  },
  "D. Cárdenas": {
    "position": "PT",
    "points": 0,
    "value": 573847
  },
  "Carvajal": {
    "position": "DF",
    "points": 0,
    "value": 3518297
  },
  "D. Ceballos": {
    "position": "MD",
    "points": 0,
    "value": 713204
  },
  "D. Martínez": {
    "position": "DF",
    "points": 0,
    "value": 479639
  },
  "Dani Olmo": {
    "position": "MD",
    "points": 0,
    "value": 33164216
  },
  "Raba": {
    "position": "DL",
    "points": 0,
    "value": 829092
  },
  "Vivian": {
    "position": "DF",
    "points": 0,
    "value": 17300199
  },
  "D. Pérez": {
    "position": "MD",
    "points": 0,
    "value": 573792
  },
  "Bladi": {
    "position": "DF",
    "points": 0,
    "value": 574390
  },
  "Affengruber": {
    "position": "DF",
    "points": 0,
    "value": 19781782
  },
  "Alaba": {
    "position": "DF",
    "points": 0,
    "value": 597449
  },
  "Davinchi": {
    "position": "DF",
    "points": 0,
    "value": 593955
  },
  "David Costas": {
    "position": "DF",
    "points": 0,
    "value": 710156
  },
  "David Delgado": {
    "position": "DF",
    "points": 0,
    "value": 572363
  },
  "Hancko": {
    "position": "DF",
    "points": 0,
    "value": 29363937
  },
  "D. Jiménez": {
    "position": "DF",
    "points": 0,
    "value": 574323
  },
  "David Carmo": {
    "position": "DF",
    "points": 0,
    "value": 1136018
  },
  "Otorbi": {
    "position": "DL",
    "points": 0,
    "value": 573460
  },
  "Huijsen": {
    "position": "DF",
    "points": 0,
    "value": 54714186
  },
  "Denis Suárez": {
    "position": "MD",
    "points": 0,
    "value": 601136
  },
  "Diego Aguado": {
    "position": "DF",
    "points": 0,
    "value": 574250
  },
  "Diego Conde": {
    "position": "PT",
    "points": 0,
    "value": 591675
  },
  "Ferrer": {
    "position": "PT",
    "points": 0,
    "value": 574286
  },
  "Kochen": {
    "position": "PT",
    "points": 0,
    "value": 573470
  },
  "Llorente": {
    "position": "DF",
    "points": 0,
    "value": 611255
  },
  "Dieguito": {
    "position": "MD",
    "points": 0,
    "value": 408007
  },
  "Morcillo": {
    "position": "DL",
    "points": 0,
    "value": 574286
  },
  "Pampin": {
    "position": "MD",
    "points": 0,
    "value": 573777
  },
  "Rico": {
    "position": "DF",
    "points": 0,
    "value": 1310735
  },
  "Simeone": {
    "position": "UNK",
    "points": 0,
    "value": 598827
  },
  "Foulquier": {
    "position": "DF",
    "points": 0,
    "value": 794798
  },
  "Stamatakis": {
    "position": "PT",
    "points": 0,
    "value": 572760
  },
  "Djene": {
    "position": "DF",
    "points": 0,
    "value": 4054835
  },
  "Livakovic": {
    "position": "PT",
    "points": 0,
    "value": 747454
  },
  "Van De Beek": {
    "position": "MD",
    "points": 0,
    "value": 580927
  },
  "Dro": {
    "position": "MD",
    "points": 0,
    "value": 578629
  },
  "Caleta-Car": {
    "position": "DF",
    "points": 0,
    "value": 788444
  },
  "Eder Aller": {
    "position": "PT",
    "points": 0,
    "value": 575749
  },
  "E. Militão": {
    "position": "DF",
    "points": 0,
    "value": 34866034
  },
  "Eder García": {
    "position": "MD",
    "points": 0,
    "value": 535685
  },
  "Eder Sarabia": {
    "position": "UNK",
    "points": 0,
    "value": 576395
  },
  "Edu Altozano": {
    "position": "MD",
    "points": 0,
    "value": 573290
  },
  "Coudet": {
    "position": "UNK",
    "points": 0,
    "value": 586976
  },
  "Egoitz M.l.": {
    "position": "DF",
    "points": 0,
    "value": 558069
  },
  "Bujan": {
    "position": "DL",
    "points": 0,
    "value": 535685
  },
  "Cömert": {
    "position": "DF",
    "points": 0,
    "value": 577084
  },
  "E. Bailly": {
    "position": "DF",
    "points": 0,
    "value": 582794
  },
  "Eric": {
    "position": "DF",
    "points": 0,
    "value": 65809355
  },
  "Cardoso": {
    "position": "DF",
    "points": 0,
    "value": 598900
  },
  "Redondo": {
    "position": "MD",
    "points": 0,
    "value": 588138
  },
  "Valverde": {
    "position": "MD",
    "points": 0,
    "value": 77011956
  },
  "F. Viñas": {
    "position": "DL",
    "points": 0,
    "value": 614322
  },
  "Félix": {
    "position": "DF",
    "points": 0,
    "value": 577216
  },
  "F. Mendy": {
    "position": "DF",
    "points": 0,
    "value": 599173
  },
  "F. Calero": {
    "position": "DF",
    "points": 0,
    "value": 2555719
  },
  "Ferri": {
    "position": "MD",
    "points": 0,
    "value": 467610
  },
  "Ferran Jutglà": {
    "position": "DL",
    "points": 0,
    "value": 1214770
  },
  "Ferran": {
    "position": "DL",
    "points": 0,
    "value": 110006903
  },
  "Ugrinic": {
    "position": "MD",
    "points": 0,
    "value": 600481
  },
  "Fran García": {
    "position": "DF",
    "points": 0,
    "value": 671506
  },
  "Fran González": {
    "position": "PT",
    "points": 0,
    "value": 573294
  },
  "Fran Pérez": {
    "position": "MD",
    "points": 0,
    "value": 619405
  },
  "Isco": {
    "position": "MD",
    "points": 0,
    "value": 23101093
  },
  "Franco Cervi": {
    "position": "DL",
    "points": 0,
    "value": 575685
  },
  "F. Mastantuono": {
    "position": "DL",
    "points": 0,
    "value": 6773302
  },
  "F. De Jong": {
    "position": "MD",
    "points": 0,
    "value": 51736231
  },
  "Suazo": {
    "position": "DF",
    "points": 0,
    "value": 2732579
  },
  "Mikautadze": {
    "position": "DL",
    "points": 0,
    "value": 12870488
  },
  "Peque": {
    "position": "DL",
    "points": 0,
    "value": 584766
  },
  "Gumbau": {
    "position": "MD",
    "points": 0,
    "value": 579344
  },
  "Gerard Martín": {
    "position": "DF",
    "points": 0,
    "value": 19167722
  },
  "Germán": {
    "position": "PT",
    "points": 0,
    "value": 574400
  },
  "German V.": {
    "position": "MD",
    "points": 0,
    "value": 40012203
  },
  "Raspadori": {
    "position": "DL",
    "points": 0,
    "value": 665484
  },
  "Gibi": {
    "position": "DF",
    "points": 0,
    "value": 572755
  },
  "Lo Celso": {
    "position": "MD",
    "points": 0,
    "value": 23750352
  },
  "Koyalipou": {
    "position": "DL",
    "points": 0,
    "value": 591573
  },
  "Guedes": {
    "position": "MD",
    "points": 0,
    "value": 19523390
  },
  "Gonzalo": {
    "position": "DL",
    "points": 0,
    "value": 1507856
  },
  "Gorka Carrera": {
    "position": "DL",
    "points": 0,
    "value": 605859
  },
  "Grady Diangana": {
    "position": "DL",
    "points": 0,
    "value": 609788
  },
  "Swiderski": {
    "position": "PT",
    "points": 0,
    "value": 572755
  },
  "Guille Fernández": {
    "position": "MD",
    "points": 0,
    "value": 573493
  },
  "Guillermo Almada": {
    "position": "UNK",
    "points": 0,
    "value": 819080
  },
  "Hassan": {
    "position": "MD",
    "points": 0,
    "value": 1018910
  },
  "Bellerín": {
    "position": "DF",
    "points": 0,
    "value": 11837424
  },
  "Héctor Fort": {
    "position": "DF",
    "points": 0,
    "value": 1173301
  },
  "Moldovan": {
    "position": "PT",
    "points": 0,
    "value": 577320
  },
  "H. González": {
    "position": "MD",
    "points": 0,
    "value": 558069
  },
  "Hugo Lopez": {
    "position": "MD",
    "points": 0,
    "value": 572718
  },
  "H. Rincón": {
    "position": "DF",
    "points": 0,
    "value": 577216
  },
  "Solozabal": {
    "position": "MD",
    "points": 0,
    "value": 503679
  },
  "Hugo Sotelo": {
    "position": "MD",
    "points": 0,
    "value": 1976009
  },
  "Huseini": {
    "position": "DF",
    "points": 0,
    "value": 558069
  },
  "Iago Aspas": {
    "position": "DL",
    "points": 0,
    "value": 4415895
  },
  "Aguirre": {
    "position": "MD",
    "points": 0,
    "value": 408007
  },
  "Ibon Sánchez": {
    "position": "DL",
    "points": 0,
    "value": 571357
  },
  "I. Benito": {
    "position": "DL",
    "points": 0,
    "value": 575528
  },
  "Iker Losada": {
    "position": "DL",
    "points": 0,
    "value": 579396
  },
  "Monreal": {
    "position": "DF",
    "points": 0,
    "value": 572822
  },
  "I. Akhomach": {
    "position": "DL",
    "points": 0,
    "value": 581810
  },
  "Kostis": {
    "position": "DF",
    "points": 0,
    "value": 573540
  },
  "Salhi": {
    "position": "DF",
    "points": 0,
    "value": 573175
  },
  "Ilyas": {
    "position": "DL",
    "points": 0,
    "value": 609170
  },
  "Iñaki Peña": {
    "position": "PT",
    "points": 0,
    "value": 2349174
  },
  "Arguibide": {
    "position": "DF",
    "points": 0,
    "value": 566028
  },
  "I. Lekue": {
    "position": "DF",
    "points": 0,
    "value": 583435
  },
  "Ionut Radu": {
    "position": "PT",
    "points": 0,
    "value": 11272524
  },
  "Isaac": {
    "position": "DL",
    "points": 0,
    "value": 1829389
  },
  "Isi": {
    "position": "DL",
    "points": 0,
    "value": 9028918
  },
  "Ismael": {
    "position": "DF",
    "points": 0,
    "value": 577317
  },
  "Sierra": {
    "position": "DF",
    "points": 0,
    "value": 572363
  },
  "Iván": {
    "position": "MD",
    "points": 0,
    "value": 573290
  },
  "Cuéllar": {
    "position": "PT",
    "points": 0,
    "value": 574614
  },
  "I. Romero": {
    "position": "DL",
    "points": 0,
    "value": 3107206
  },
  "Izei": {
    "position": "MD",
    "points": 0,
    "value": 479639
  },
  "Oblak": {
    "position": "PT",
    "points": 0,
    "value": 22662877
  },
  "Jan Virgili": {
    "position": "DL",
    "points": 0,
    "value": 10283069
  },
  "Jandro": {
    "position": "MD",
    "points": 0,
    "value": 408007
  },
  "Jano": {
    "position": "MD",
    "points": 0,
    "value": 572865
  },
  "Javi Galán": {
    "position": "DF",
    "points": 0,
    "value": 875526
  },
  "Javi Guerra": {
    "position": "MD",
    "points": 0,
    "value": 4268288
  },
  "Javi H.": {
    "position": "DL",
    "points": 0,
    "value": 575023
  },
  "Javi Llabrés": {
    "position": "DL",
    "points": 0,
    "value": 574284
  },
  "Javi López": {
    "position": "DF",
    "points": 0,
    "value": 578276
  },
  "Javi Muñoz": {
    "position": "MD",
    "points": 0,
    "value": 586948
  },
  "Puado": {
    "position": "MD",
    "points": 0,
    "value": 5380554
  },
  "Javi Rueda": {
    "position": "DF",
    "points": 0,
    "value": 3854071
  },
  "Javi Serrano": {
    "position": "MD",
    "points": 0,
    "value": 575658
  },
  "J. Boñar": {
    "position": "DF",
    "points": 0,
    "value": 546123
  },
  "Javi Navarro": {
    "position": "PT",
    "points": 0,
    "value": 572363
  },
  "Olaizola": {
    "position": "DF",
    "points": 0,
    "value": 572363
  },
  "Sarasa": {
    "position": "DL",
    "points": 0,
    "value": 575749
  },
  "J. Ives Valou": {
    "position": "DF",
    "points": 0,
    "value": 572827
  },
  "Jeremy Toljan": {
    "position": "DF",
    "points": 0,
    "value": 902933
  },
  "Areso": {
    "position": "DF",
    "points": 0,
    "value": 4430269
  },
  "Fortea": {
    "position": "DF",
    "points": 0,
    "value": 574006
  },
  "J. Vázquez": {
    "position": "DF",
    "points": 0,
    "value": 618835
  },
  "Jhon Solis": {
    "position": "MD",
    "points": 0,
    "value": 573682
  },
  "Letacek": {
    "position": "PT",
    "points": 0,
    "value": 574273
  },
  "Joan García": {
    "position": "PT",
    "points": 0,
    "value": 64774418
  },
  "Jordán": {
    "position": "MD",
    "points": 0,
    "value": 579182
  },
  "Joan Martínez": {
    "position": "DF",
    "points": 0,
    "value": 642453
  },
  "Joan Ruiz": {
    "position": "MD",
    "points": 0,
    "value": 573730
  },
  "Oso": {
    "position": "DF",
    "points": 0,
    "value": 587106
  },
  "Fontanet": {
    "position": "DF",
    "points": 0,
    "value": 408007
  },
  "Joel Roca": {
    "position": "DL",
    "points": 0,
    "value": 604044
  },
  "J. Mojica": {
    "position": "DF",
    "points": 0,
    "value": 10355018
  },
  "John C.": {
    "position": "DF",
    "points": 0,
    "value": 575390
  }
};
const MARKET_TRENDS = {
  "Pedri": {
    "trend": 995376,
    "trendPct": 0.61
  },
  "Remiro": {
    "trend": -90940,
    "trendPct": -1.5
  },
  "Iñaki Williams": {
    "trend": -121418,
    "trendPct": -1.24
  },
  "David Soria": {
    "trend": -86539,
    "trendPct": -0.99
  },
  "Berenguer": {
    "trend": -357325,
    "trendPct": -1.33
  },
  "Raíllo": {
    "trend": -102761,
    "trendPct": -1.42
  },
  "Sergio Herrera": {
    "trend": -42232,
    "trendPct": -0.28
  },
  "Sergio Gómez": {
    "trend": -38622,
    "trendPct": -0.71
  },
  "Courtois": {
    "trend": 642168,
    "trendPct": 1.36
  },
  "Lejeune": {
    "trend": 776976,
    "trendPct": 2.03
  },
  "Kubo": {
    "trend": 821933,
    "trendPct": 3.45
  },
  "Pau Cubarsí": {
    "trend": 545303,
    "trendPct": 1.43
  },
  "Rubén García": {
    "trend": 255472,
    "trendPct": 3.19
  },
  "Darder": {
    "trend": -139048,
    "trendPct": -1.29
  },
  "Diego López": {
    "trend": -88838,
    "trendPct": -2.09
  },
  "Álvaro García": {
    "trend": -148890,
    "trendPct": -0.82
  },
  "Rioja": {
    "trend": -181486,
    "trendPct": -1.75
  },
  "Arambarri": {
    "trend": 284893,
    "trendPct": 1.45
  },
  "Marcos Llorente": {
    "trend": 211233,
    "trendPct": 0.29
  },
  "De Frutos": {
    "trend": 585137,
    "trendPct": 2.25
  },
  "Kumbulla": {
    "trend": 563,
    "trendPct": 0.1
  },
  "Marcos Alonso": {
    "trend": 185619,
    "trendPct": 0.84
  },
  "Cardona": {
    "trend": -116987,
    "trendPct": -1.29
  },
  "Álex Balde": {
    "trend": 961631,
    "trendPct": 2.18
  },
  "Giuliano": {
    "trend": -350556,
    "trendPct": -0.61
  },
  "Boyomo": {
    "trend": -175427,
    "trendPct": -2.02
  },
  "Tchouaméni": {
    "trend": 838883,
    "trendPct": 1.5
  },
  "Valjent": {
    "trend": -31427,
    "trendPct": -0.94
  },
  "Tárrega": {
    "trend": -139778,
    "trendPct": -2.09
  },
  "Carmona": {
    "trend": -139087,
    "trendPct": -1.84
  },
  "Jofre": {
    "trend": 933,
    "trendPct": 0.16
  },
  "Comesaña": {
    "trend": -2855,
    "trendPct": -0.01
  },
  "Catena": {
    "trend": -923285,
    "trendPct": -1.6
  },
  "Guruzeta": {
    "trend": -10875,
    "trendPct": -0.73
  },
  "Parejo": {
    "trend": 8182,
    "trendPct": 1.01
  },
  "Barrios": {
    "trend": -1587634,
    "trendPct": -2.37
  },
  "Sow": {
    "trend": -629,
    "trendPct": -0.1
  },
  "Juan Iglesias": {
    "trend": -16868,
    "trendPct": -1.65
  },
  "Jauregizar": {
    "trend": -366976,
    "trendPct": -1.17
  },
  "Torró": {
    "trend": -4346,
    "trendPct": -0.52
  },
  "Hansi Flick": {
    "trend": -1847,
    "trendPct": -0.29
  },
  "Arnau": {
    "trend": -4888,
    "trendPct": -0.38
  },
  "Yuri": {
    "trend": -293134,
    "trendPct": -2.67
  },
  "Daley Blind": {
    "trend": -14423,
    "trendPct": -1.25
  },
  "Iván Martín": {
    "trend": -29295,
    "trendPct": -1.22
  },
  "Samu Costa": {
    "trend": -25839,
    "trendPct": -1.32
  },
  "Fran Beltrán": {
    "trend": 299,
    "trendPct": 0.05
  },
  "Pedrosa": {
    "trend": 920,
    "trendPct": 0.16
  },
  "David López": {
    "trend": 31,
    "trendPct": 0.01
  },
  "Javi Rodríguez": {
    "trend": 132,
    "trendPct": 0.02
  },
  "Almeida": {
    "trend": -5836,
    "trendPct": -0.63
  },
  "De Galarreta": {
    "trend": -157642,
    "trendPct": -1.92
  },
  "Abel Bretones": {
    "trend": -13263,
    "trendPct": -1.42
  },
  "Hugo Duro": {
    "trend": -127714,
    "trendPct": -2.5
  },
  "Chavarría": {
    "trend": -88158,
    "trendPct": -0.49
  },
  "Juanlu": {
    "trend": -8339,
    "trendPct": -1.03
  },
  "Bartra": {
    "trend": -76602,
    "trendPct": -0.21
  },
  "Altimira": {
    "trend": -38675,
    "trendPct": -2.47
  },
  "Tsygankov": {
    "trend": 108635,
    "trendPct": 2.09
  },
  "Blanco": {
    "trend": -28617,
    "trendPct": -0.96
  },
  "Conor Gallagher": {
    "trend": -20103,
    "trendPct": -1.82
  },
  "Agirrezabala": {
    "trend": -218734,
    "trendPct": -2.69
  },
  "Sivera": {
    "trend": -64623,
    "trendPct": -1.63
  },
  "Tenaglia": {
    "trend": -225412,
    "trendPct": -1.42
  },
  "Ernesto Valverde": {
    "trend": 334,
    "trendPct": 0.06
  },
  "Zubeldia": {
    "trend": 7549,
    "trendPct": 0.22
  },
  "Guridi": {
    "trend": 182,
    "trendPct": 0.03
  },
  "Guevara": {
    "trend": 744,
    "trendPct": 0.13
  },
  "Óscar Valentín": {
    "trend": -4909,
    "trendPct": -0.52
  },
  "Prados": {
    "trend": 849,
    "trendPct": 0.15
  },
  "El Hilali": {
    "trend": -8250,
    "trendPct": -0.31
  },
  "Arda Güler": {
    "trend": -1110839,
    "trendPct": -1.37
  },
  "Le Normand": {
    "trend": -234330,
    "trendPct": -1.89
  },
  "Barrenetxea": {
    "trend": -455675,
    "trendPct": -1.12
  },
  "Hugo Alvarez": {
    "trend": -3079,
    "trendPct": -0.45
  },
  "Fornals": {
    "trend": -1157945,
    "trendPct": -1.04
  },
  "Moncayola": {
    "trend": 22917,
    "trendPct": 0.39
  },
  "Marcelino": {
    "trend": 263,
    "trendPct": 0.04
  },
  "Asencio": {
    "trend": 144731,
    "trendPct": 1.99
  },
  "Morlanes": {
    "trend": -251,
    "trendPct": -0.04
  },
  "Gerard": {
    "trend": 122132,
    "trendPct": 0.3
  },
  "Asprilla": {
    "trend": -2907,
    "trendPct": -0.43
  },
  "Gayá": {
    "trend": -27263,
    "trendPct": -1.77
  },
  "Jagoba Arrasate": {
    "trend": 651,
    "trendPct": 0.11
  },
  "Unai Simón": {
    "trend": -211848,
    "trendPct": -1.53
  },
  "Claudio Giraldez": {
    "trend": 729,
    "trendPct": 0.13
  },
  "Domingos Duarte": {
    "trend": -40555,
    "trendPct": -2.51
  },
  "Camavinga": {
    "trend": 930036,
    "trendPct": 5.01
  },
  "Fermín": {
    "trend": 8923,
    "trendPct": 0.01
  },
  "Iñigo Perez": {
    "trend": 743,
    "trendPct": 0.13
  },
  "Mouriño": {
    "trend": 1422,
    "trendPct": 0.01
  },
  "José Bordalás": {
    "trend": 906,
    "trendPct": 0.16
  },
  "Vesga": {
    "trend": 922,
    "trendPct": 0.16
  },
  "Pol Lozano": {
    "trend": -5413,
    "trendPct": -0.74
  },
  "Moi Gómez": {
    "trend": -16729,
    "trendPct": -1.64
  },
  "Turrientes": {
    "trend": 604,
    "trendPct": 0.1
  },
  "Moussa Diarra": {
    "trend": 1035,
    "trendPct": 0.18
  },
  "Gavi": {
    "trend": -10113,
    "trendPct": -1.19
  },
  "Balliu": {
    "trend": 715,
    "trendPct": 0.12
  },
  "Cucho": {
    "trend": 1360091,
    "trendPct": 1.29
  },
  "Francés": {
    "trend": 955,
    "trendPct": 0.17
  },
  "Portu": {
    "trend": 837,
    "trendPct": 0.14
  },
  "Iker Muñoz": {
    "trend": 985,
    "trendPct": 0.17
  },
  "Iván Villar": {
    "trend": 1008,
    "trendPct": 0.18
  },
  "Edu Expósito": {
    "trend": 1428412,
    "trendPct": 2.03
  },
  "F. Garcés": {
    "trend": -3856,
    "trendPct": -0.55
  },
  "Ramón Martínez": {
    "trend": 1145,
    "trendPct": 0.2
  },
  "Aitor Fdez": {
    "trend": 971,
    "trendPct": 0.17
  },
  "Yoel Lago": {
    "trend": 1103,
    "trendPct": 0.19
  },
  "Aarón": {
    "trend": -105960,
    "trendPct": -0.38
  },
  "Ez Abde": {
    "trend": -647042,
    "trendPct": -1.82
  },
  "A. Rebbach": {
    "trend": 1022,
    "trendPct": 0.18
  },
  "A. Abqar": {
    "trend": -14061,
    "trendPct": -1.48
  },
  "Abdón": {
    "trend": 981,
    "trendPct": 0.17
  },
  "A. Mumin": {
    "trend": 1033,
    "trendPct": 0.18
  },
  "Abel Ruiz": {
    "trend": 907,
    "trendPct": 0.16
  },
  "Kamara": {
    "trend": -195,
    "trendPct": -0.03
  },
  "Adam B.": {
    "trend": 1074,
    "trendPct": 0.19
  },
  "Adama": {
    "trend": 1074,
    "trendPct": 0.19
  },
  "Januzaj": {
    "trend": 420,
    "trendPct": 0.07
  },
  "A. Alti": {
    "trend": 783,
    "trendPct": 0.13
  },
  "Dela": {
    "trend": 1009,
    "trendPct": 0.18
  },
  "A. Liso": {
    "trend": -57764,
    "trendPct": -2.0
  },
  "Adrián Molina": {
    "trend": 1138,
    "trendPct": 0.2
  },
  "Adrián": {
    "trend": 1200,
    "trendPct": 0.21
  },
  "Aihen": {
    "trend": 756,
    "trendPct": 0.13
  },
  "Aimar Blázquez": {
    "trend": 1125,
    "trendPct": 0.2
  },
  "Aimar": {
    "trend": -5775,
    "trendPct": -0.1
  },
  "Fraga": {
    "trend": 1159,
    "trendPct": 0.2
  },
  "Mañas": {
    "trend": 5022,
    "trendPct": 1.06
  },
  "Paredes": {
    "trend": -146791,
    "trendPct": -1.7
  },
  "Aitor Ruibal": {
    "trend": 56909,
    "trendPct": 5.88
  },
  "Akor": {
    "trend": -9573,
    "trendPct": -1.14
  },
  "Alan Matturro": {
    "trend": 615,
    "trendPct": 0.11
  },
  "Alassane": {
    "trend": 8007,
    "trendPct": 2.0
  },
  "Albert": {
    "trend": 1073,
    "trendPct": 0.19
  },
  "Alberto F.": {
    "trend": 1109,
    "trendPct": 0.19
  },
  "A. Moleiro": {
    "trend": 999298,
    "trendPct": 0.94
  },
  "A. Reina": {
    "trend": 643,
    "trendPct": 0.11
  },
  "Risco": {
    "trend": 1113,
    "trendPct": 0.19
  },
  "Febas": {
    "trend": 89205,
    "trendPct": 0.76
  },
  "A. Iturbe": {
    "trend": 1098,
    "trendPct": 0.19
  },
  "Panach": {
    "trend": 2006,
    "trendPct": 0.36
  },
  "Rego": {
    "trend": 1034,
    "trendPct": 0.18
  },
  "Álex Sancris": {
    "trend": 522,
    "trendPct": 0.09
  },
  "Puri?": {
    "trend": -518,
    "trendPct": -0.08
  },
  "Andreev": {
    "trend": 1078,
    "trendPct": 0.19
  },
  "Alessio Lisci": {
    "trend": 774,
    "trendPct": 0.13
  },
  "Álex Baena": {
    "trend": 1302623,
    "trendPct": 2.22
  },
  "Alex Costa": {
    "trend": 1099,
    "trendPct": 0.19
  },
  "A. Fores": {
    "trend": 1097,
    "trendPct": 0.19
  },
  "Lebarbier": {
    "trend": 1218,
    "trendPct": 0.21
  },
  "Alex Marchal": {
    "trend": 1565,
    "trendPct": 0.28
  },
  "Alex Moreno": {
    "trend": -10237,
    "trendPct": -1.2
  },
  "Padilla": {
    "trend": 883,
    "trendPct": 0.15
  },
  "A. Primo": {
    "trend": 715,
    "trendPct": 0.12
  },
  "Sørloth": {
    "trend": 26283,
    "trendPct": 0.44
  },
  "Alemâo": {
    "trend": -1877,
    "trendPct": -0.29
  },
  "Alexis Sánchez": {
    "trend": -24787,
    "trendPct": -1.05
  },
  "Alfon": {
    "trend": -5617,
    "trendPct": -0.76
  },
  "Pacha": {
    "trend": 891,
    "trendPct": 0.15
  },
  "A. Pedraza": {
    "trend": 31935,
    "trendPct": 2.37
  },
  "A. Houary": {
    "trend": 954,
    "trendPct": 0.17
  },
  "Nyom": {
    "trend": 1127,
    "trendPct": 0.2
  },
  "Á. Carreras": {
    "trend": 1739767,
    "trendPct": 2.36
  },
  "A. Ferllo": {
    "trend": 806,
    "trendPct": 0.14
  },
  "Álvaro Nuñez": {
    "trend": 50308,
    "trendPct": 0.21
  },
  "Odriozola": {
    "trend": 929,
    "trendPct": 0.16
  },
  "Álvaro": {
    "trend": 66199,
    "trendPct": 2.34
  },
  "Á. Valles": {
    "trend": -6717,
    "trendPct": -0.2
  },
  "Gorosabel": {
    "trend": 159,
    "trendPct": 0.03
  },
  "André Silva": {
    "trend": -86102,
    "trendPct": -2.1
  },
  "Christensen": {
    "trend": -6473,
    "trendPct": -0.85
  },
  "Ratiu": {
    "trend": 543049,
    "trendPct": 1.19
  },
  "A. Castrín": {
    "trend": 286,
    "trendPct": 0.05
  },
  "Lunin": {
    "trend": 556,
    "trendPct": 0.09
  },
  "A. Arcos": {
    "trend": 5022,
    "trendPct": 1.06
  },
  "A. Fortuño": {
    "trend": 1044,
    "trendPct": 0.18
  },
  "Á. Ortiz": {
    "trend": 770,
    "trendPct": 0.13
  },
  "Budimir": {
    "trend": -56607,
    "trendPct": -0.31
  },
  "Griezmann": {
    "trend": -447349,
    "trendPct": -1.75
  },
  "Toni Lato": {
    "trend": 1047,
    "trendPct": 0.18
  },
  "A. Martinez": {
    "trend": 1127,
    "trendPct": 0.2
  },
  "Rüdiger": {
    "trend": 615707,
    "trendPct": 2.95
  },
  "Salguero": {
    "trend": 1754,
    "trendPct": 0.32
  },
  "Antonio Sánchez": {
    "trend": 954,
    "trendPct": 0.17
  },
  "A. Roca": {
    "trend": 1140,
    "trendPct": 0.2
  },
  "Antony": {
    "trend": -1427875,
    "trendPct": -1.31
  },
  "Aritz": {
    "trend": 889,
    "trendPct": 0.15
  },
  "Mariezkurrena": {
    "trend": -536,
    "trendPct": -0.09
  },
  "Arnau Tenas": {
    "trend": -997,
    "trendPct": -0.16
  },
  "Danjuma": {
    "trend": -304552,
    "trendPct": -2.02
  },
  "Zakharyan": {
    "trend": 707,
    "trendPct": 0.12
  },
  "Asier Hierro": {
    "trend": 2687,
    "trendPct": 0.5
  },
  "A. Osambela": {
    "trend": 1155,
    "trendPct": 0.2
  },
  "A. Batalla": {
    "trend": -107275,
    "trendPct": -0.78
  },
  "Witsel": {
    "trend": -35542,
    "trendPct": -1.14
  },
  "Laporte": {
    "trend": -350417,
    "trendPct": -2.66
  },
  "Ayoze": {
    "trend": -181544,
    "trendPct": -0.71
  },
  "Ounahi": {
    "trend": -209192,
    "trendPct": -2.57
  },
  "Diaby": {
    "trend": 1086,
    "trendPct": 0.19
  },
  "Santamaría": {
    "trend": -7652,
    "trendPct": -0.97
  },
  "Mendy": {
    "trend": -10795,
    "trendPct": -0.97
  },
  "B. Iglesias": {
    "trend": 736116,
    "trendPct": 4.58
  },
  "B. Mayoral": {
    "trend": -117091,
    "trendPct": -2.75
  },
  "Brahim": {
    "trend": -39286,
    "trendPct": -1.89
  },
  "Brais Méndez": {
    "trend": -166925,
    "trendPct": -0.63
  },
  "Bryan Gil": {
    "trend": -15570,
    "trendPct": -0.97
  },
  "Bryan": {
    "trend": 59817,
    "trendPct": 1.67
  },
  "Calebe": {
    "trend": 954,
    "trendPct": 0.17
  },
  "Starfelt": {
    "trend": 44926,
    "trendPct": 1.72
  },
  "Aleñá": {
    "trend": -73165,
    "trendPct": -2.11
  },
  "C. Alvarez": {
    "trend": 96757,
    "trendPct": 1.53
  },
  "Ballestero": {
    "trend": 1139,
    "trendPct": 0.2
  },
  "Protesoni": {
    "trend": 850,
    "trendPct": 0.15
  },
  "Carlos Corberán": {
    "trend": 1057,
    "trendPct": 0.18
  },
  "C. Dominguez": {
    "trend": 968,
    "trendPct": 0.17
  },
  "C. Espí": {
    "trend": 1060,
    "trendPct": 0.18
  },
  "Carlos Macià": {
    "trend": -3313,
    "trendPct": -0.49
  },
  "Carlos Martín": {
    "trend": 1047,
    "trendPct": 0.18
  },
  "C. Romero": {
    "trend": 670351,
    "trendPct": 1.65
  },
  "C. Soler": {
    "trend": -29252,
    "trendPct": -0.3
  },
  "Carlos V.": {
    "trend": -60680,
    "trendPct": -0.64
  },
  "Cayetano": {
    "trend": 1139,
    "trendPct": 0.2
  },
  "Bakambu": {
    "trend": 434,
    "trendPct": 0.07
  },
  "Azpilicueta": {
    "trend": -13161,
    "trendPct": -1.42
  },
  "Pickel": {
    "trend": 665,
    "trendPct": 0.11
  },
  "Ejuke": {
    "trend": -3167,
    "trendPct": -0.47
  },
  "Chimy Ávila": {
    "trend": 646,
    "trendPct": 0.11
  },
  "Riedel": {
    "trend": -17441,
    "trendPct": -1.68
  },
  "Lenglet": {
    "trend": -23772,
    "trendPct": -1.99
  },
  "Coba": {
    "trend": 1129,
    "trendPct": 0.2
  },
  "Stuani": {
    "trend": 475,
    "trendPct": 0.08
  },
  "C. Rivero": {
    "trend": 1096,
    "trendPct": 0.19
  },
  "Damian": {
    "trend": 988,
    "trendPct": 0.17
  },
  "Dani Calvo": {
    "trend": 353,
    "trendPct": 0.06
  },
  "D. Cárdenas": {
    "trend": 1097,
    "trendPct": 0.19
  },
  "Carvajal": {
    "trend": 101983,
    "trendPct": 2.99
  },
  "D. Ceballos": {
    "trend": -4710,
    "trendPct": -0.66
  },
  "D. Martínez": {
    "trend": 5022,
    "trendPct": 1.06
  },
  "Dani Olmo": {
    "trend": 1537271,
    "trendPct": 4.86
  },
  "Raba": {
    "trend": -9539,
    "trendPct": -1.14
  },
  "Vivian": {
    "trend": -338354,
    "trendPct": -1.92
  },
  "D. Pérez": {
    "trend": 1099,
    "trendPct": 0.19
  },
  "Bladi": {
    "trend": 1074,
    "trendPct": 0.19
  },
  "Affengruber": {
    "trend": -178372,
    "trendPct": -0.89
  },
  "Alaba": {
    "trend": 113,
    "trendPct": 0.02
  },
  "Davinchi": {
    "trend": 259,
    "trendPct": 0.04
  },
  "David Costas": {
    "trend": 4713,
    "trendPct": 0.67
  },
  "David Delgado": {
    "trend": 1159,
    "trendPct": 0.2
  },
  "Hancko": {
    "trend": -436539,
    "trendPct": -1.46
  },
  "D. Jiménez": {
    "trend": 1077,
    "trendPct": 0.19
  },
  "David Carmo": {
    "trend": -20092,
    "trendPct": -1.74
  },
  "Otorbi": {
    "trend": 1113,
    "trendPct": 0.19
  },
  "Huijsen": {
    "trend": -1037698,
    "trendPct": -1.86
  },
  "Denis Suárez": {
    "trend": -40,
    "trendPct": -0.01
  },
  "Diego Aguado": {
    "trend": 1080,
    "trendPct": 0.19
  },
  "Diego Conde": {
    "trend": 354,
    "trendPct": 0.06
  },
  "Ferrer": {
    "trend": 1078,
    "trendPct": 0.19
  },
  "Kochen": {
    "trend": 1112,
    "trendPct": 0.19
  },
  "Llorente": {
    "trend": -462,
    "trendPct": -0.08
  },
  "Dieguito": {
    "trend": 8007,
    "trendPct": 2.0
  },
  "Morcillo": {
    "trend": 1078,
    "trendPct": 0.19
  },
  "Pampin": {
    "trend": 1100,
    "trendPct": 0.19
  },
  "Rico": {
    "trend": -23506,
    "trendPct": -1.76
  },
  "Simeone": {
    "trend": 56,
    "trendPct": 0.01
  },
  "Foulquier": {
    "trend": -8110,
    "trendPct": -1.01
  },
  "Stamatakis": {
    "trend": 1142,
    "trendPct": 0.2
  },
  "Djene": {
    "trend": -111546,
    "trendPct": -2.68
  },
  "Livakovic": {
    "trend": -6137,
    "trendPct": -0.81
  },
  "Van De Beek": {
    "trend": 802,
    "trendPct": 0.14
  },
  "Dro": {
    "trend": 897,
    "trendPct": 0.16
  },
  "Caleta-Car": {
    "trend": -7845,
    "trendPct": -0.99
  },
  "Eder Aller": {
    "trend": 1017,
    "trendPct": 0.18
  },
  "E. Militão": {
    "trend": 621532,
    "trendPct": 1.81
  },
  "Eder García": {
    "trend": 2687,
    "trendPct": 0.5
  },
  "Eder Sarabia": {
    "trend": 991,
    "trendPct": 0.17
  },
  "Edu Altozano": {
    "trend": 1120,
    "trendPct": 0.2
  },
  "Coudet": {
    "trend": 550,
    "trendPct": 0.09
  },
  "Egoitz M.l.": {
    "trend": 1754,
    "trendPct": 0.32
  },
  "Bujan": {
    "trend": 2687,
    "trendPct": 0.5
  },
  "Cömert": {
    "trend": 962,
    "trendPct": 0.17
  },
  "E. Bailly": {
    "trend": 724,
    "trendPct": 0.12
  },
  "Eric": {
    "trend": 787247,
    "trendPct": 1.21
  },
  "Cardoso": {
    "trend": 53,
    "trendPct": 0.01
  },
  "Redondo": {
    "trend": 501,
    "trendPct": 0.09
  },
  "Valverde": {
    "trend": 2153051,
    "trendPct": 2.88
  },
  "F. Viñas": {
    "trend": -590,
    "trendPct": -0.1
  },
  "Félix": {
    "trend": 956,
    "trendPct": 0.17
  },
  "F. Mendy": {
    "trend": 41,
    "trendPct": 0.01
  },
  "F. Calero": {
    "trend": 42766,
    "trendPct": 1.7
  },
  "Ferri": {
    "trend": 5523,
    "trendPct": 1.2
  },
  "Ferran Jutglà": {
    "trend": -25608,
    "trendPct": -2.06
  },
  "Ferran": {
    "trend": -494392,
    "trendPct": -0.45
  },
  "Ugrinic": {
    "trend": -13,
    "trendPct": -0.0
  },
  "Fran García": {
    "trend": -2972,
    "trendPct": -0.44
  },
  "Fran González": {
    "trend": 1120,
    "trendPct": 0.2
  },
  "Fran Pérez": {
    "trend": -802,
    "trendPct": -0.13
  },
  "Isco": {
    "trend": -576322,
    "trendPct": -2.43
  },
  "Franco Cervi": {
    "trend": 1020,
    "trendPct": 0.18
  },
  "F. Mastantuono": {
    "trend": -151893,
    "trendPct": -2.19
  },
  "F. De Jong": {
    "trend": 263215,
    "trendPct": 0.51
  },
  "Suazo": {
    "trend": -76811,
    "trendPct": -2.73
  },
  "Mikautadze": {
    "trend": 345438,
    "trendPct": 2.76
  },
  "Peque": {
    "trend": 642,
    "trendPct": 0.11
  },
  "Gumbau": {
    "trend": 868,
    "trendPct": 0.15
  },
  "Gerard Martín": {
    "trend": 669240,
    "trendPct": 3.62
  },
  "Germán": {
    "trend": 1074,
    "trendPct": 0.19
  },
  "German V.": {
    "trend": 453058,
    "trendPct": 1.15
  },
  "Raspadori": {
    "trend": -2721,
    "trendPct": -0.41
  },
  "Gibi": {
    "trend": 1142,
    "trendPct": 0.2
  },
  "Lo Celso": {
    "trend": -373824,
    "trendPct": -1.55
  },
  "Koyalipou": {
    "trend": 358,
    "trendPct": 0.06
  },
  "Guedes": {
    "trend": 438645,
    "trendPct": 2.3
  },
  "Gonzalo": {
    "trend": 187114,
    "trendPct": 14.17
  },
  "Gorka Carrera": {
    "trend": -237,
    "trendPct": -0.04
  },
  "Grady Diangana": {
    "trend": -401,
    "trendPct": -0.07
  },
  "Swiderski": {
    "trend": 1142,
    "trendPct": 0.2
  },
  "Guille Fernández": {
    "trend": 1111,
    "trendPct": 0.19
  },
  "Guillermo Almada": {
    "trend": -9121,
    "trendPct": -1.1
  },
  "Hassan": {
    "trend": -17448,
    "trendPct": -1.68
  },
  "Bellerín": {
    "trend": -138150,
    "trendPct": -1.15
  },
  "Héctor Fort": {
    "trend": -23881,
    "trendPct": -1.99
  },
  "Moldovan": {
    "trend": 952,
    "trendPct": 0.17
  },
  "H. González": {
    "trend": 1754,
    "trendPct": 0.32
  },
  "Hugo Lopez": {
    "trend": 1144,
    "trendPct": 0.2
  },
  "H. Rincón": {
    "trend": 956,
    "trendPct": 0.17
  },
  "Solozabal": {
    "trend": 4020,
    "trendPct": 0.8
  },
  "Hugo Sotelo": {
    "trend": -56414,
    "trendPct": -2.78
  },
  "Huseini": {
    "trend": 1754,
    "trendPct": 0.32
  },
  "Iago Aspas": {
    "trend": -36818,
    "trendPct": -0.83
  },
  "Aguirre": {
    "trend": 8007,
    "trendPct": 2.0
  },
  "Ibon Sánchez": {
    "trend": 1200,
    "trendPct": 0.21
  },
  "I. Benito": {
    "trend": 1027,
    "trendPct": 0.18
  },
  "Iker Losada": {
    "trend": 865,
    "trendPct": 0.15
  },
  "Monreal": {
    "trend": 1139,
    "trendPct": 0.2
  },
  "I. Akhomach": {
    "trend": 765,
    "trendPct": 0.13
  },
  "Kostis": {
    "trend": 1110,
    "trendPct": 0.19
  },
  "Salhi": {
    "trend": 1125,
    "trendPct": 0.2
  },
  "Ilyas": {
    "trend": -375,
    "trendPct": -0.06
  },
  "Iñaki Peña": {
    "trend": -3563,
    "trendPct": -0.15
  },
  "Arguibide": {
    "trend": 1422,
    "trendPct": 0.25
  },
  "I. Lekue": {
    "trend": 697,
    "trendPct": 0.12
  },
  "Ionut Radu": {
    "trend": 112350,
    "trendPct": 1.01
  },
  "Isaac": {
    "trend": -36089,
    "trendPct": -1.93
  },
  "Isi": {
    "trend": 31274,
    "trendPct": 0.35
  },
  "Ismael": {
    "trend": 952,
    "trendPct": 0.17
  },
  "Sierra": {
    "trend": 1159,
    "trendPct": 0.2
  },
  "Iván": {
    "trend": 1120,
    "trendPct": 0.2
  },
  "Cuéllar": {
    "trend": 1065,
    "trendPct": 0.19
  },
  "I. Romero": {
    "trend": -8378,
    "trendPct": -0.27
  },
  "Izei": {
    "trend": 5022,
    "trendPct": 1.06
  },
  "Oblak": {
    "trend": -115067,
    "trendPct": -0.51
  },
  "Jan Virgili": {
    "trend": -110345,
    "trendPct": -1.06
  },
  "Jandro": {
    "trend": 8007,
    "trendPct": 2.0
  },
  "Jano": {
    "trend": 1138,
    "trendPct": 0.2
  },
  "Javi Galán": {
    "trend": 55259,
    "trendPct": 6.74
  },
  "Javi Guerra": {
    "trend": -82105,
    "trendPct": -1.89
  },
  "Javi H.": {
    "trend": 1048,
    "trendPct": 0.18
  },
  "Javi Llabrés": {
    "trend": 1078,
    "trendPct": 0.19
  },
  "Javi López": {
    "trend": 912,
    "trendPct": 0.16
  },
  "Javi Muñoz": {
    "trend": 551,
    "trendPct": 0.09
  },
  "Puado": {
    "trend": 75484,
    "trendPct": 1.42
  },
  "Javi Rueda": {
    "trend": -26896,
    "trendPct": -0.69
  },
  "Javi Serrano": {
    "trend": 1021,
    "trendPct": 0.18
  },
  "J. Boñar": {
    "trend": 2252,
    "trendPct": 0.41
  },
  "Javi Navarro": {
    "trend": 1159,
    "trendPct": 0.2
  },
  "Olaizola": {
    "trend": 1159,
    "trendPct": 0.2
  },
  "Sarasa": {
    "trend": 1017,
    "trendPct": 0.18
  },
  "J. Ives Valou": {
    "trend": 1139,
    "trendPct": 0.2
  },
  "Jeremy Toljan": {
    "trend": -12615,
    "trendPct": -1.38
  },
  "Areso": {
    "trend": -102085,
    "trendPct": -2.25
  },
  "Fortea": {
    "trend": 1090,
    "trendPct": 0.19
  },
  "J. Vázquez": {
    "trend": -778,
    "trendPct": -0.13
  },
  "Jhon Solis": {
    "trend": 1104,
    "trendPct": 0.19
  },
  "Letacek": {
    "trend": 1079,
    "trendPct": 0.19
  },
  "Joan García": {
    "trend": 779227,
    "trendPct": 1.22
  },
  "Jordán": {
    "trend": 874,
    "trendPct": 0.15
  },
  "Joan Martínez": {
    "trend": -1762,
    "trendPct": -0.27
  },
  "Joan Ruiz": {
    "trend": 1102,
    "trendPct": 0.19
  },
  "Oso": {
    "trend": 544,
    "trendPct": 0.09
  },
  "Fontanet": {
    "trend": 8007,
    "trendPct": 2.0
  },
  "Joel Roca": {
    "trend": -162,
    "trendPct": -0.03
  },
  "J. Mojica": {
    "trend": -171584,
    "trendPct": -1.63
  },
  "John C.": {
    "trend": 1032,
    "trendPct": 0.18
  }
};
