// Auto-generated by scrape_market.py from guiafantasy.com
// Generated: 2026-05-07 08:51
// Total Players: 231
const MARKET_DATA = {
  "Pedri": 209027708,
  "Remiro": 2655632,
  "Iñaki Williams": 4527348,
  "David Soria": 4604393,
  "Berenguer": 6240258,
  "Raíllo": 1063271,
  "Sergio Herrera": 4265349,
  "Sergio Gómez": 11593047,
  "Courtois": 17328538,
  "Lejeune": 70270515,
  "Kubo": 14320844,
  "Pau Cubarsí": 71948476,
  "Rubén García": 20256134,
  "Darder": 14699931,
  "Diego López": 874552,
  "Álvaro García": 8508608,
  "Rioja": 10104258,
  "Arambarri": 73215761,
  "Marcos Llorente": 44864065,
  "De Frutos": 26025023,
  "Kumbulla": 827471,
  "Marcos Alonso": 67367643,
  "Cardona": 1888786,
  "Álex Balde": 16995975,
  "Giuliano": 36641530,
  "Boyomo": 2934469,
  "Tchouaméni": 72074886,
  "Valjent": 1137419,
  "Tárrega": 1258968,
  "Carmona": 994622,
  "Jofre": 827402,
  "Yeray": 2053802,
  "Comesaña": 67320974,
  "Catena": 38121072,
  "Guruzeta": 2094277,
  "Parejo": 841392,
  "Barrios": 17518897,
  "Sow": 946698,
  "Juan Iglesias": 1472464,
  "Jauregizar": 10089237,
  "Torró": 830612,
  "Hansi Flick": 827919,
  "Arnau": 2462886,
  "Yuri": 13433557,
  "Daley Blind": 4294886,
  "Iván Martín": 1524418,
  "Samu Costa": 1582683,
  "Fran Beltrán": 832328,
  "Pedrosa": 827403,
  "David López": 827711,
  "Javi Rodríguez": 829987,
  "Almeida": 830324,
  "De Galarreta": 6414871,
  "Abel Bretones": 830125,
  "Hugo Duro": 1109998,
  "Chavarría": 7051390,
  "Juanlu": 830347,
  "Bartra": 14357073,
  "Altimira": 839619,
  "Tsygankov": 5428604,
  "Blanco": 1283641,
  "Agirrezabala": 917280,
  "Sivera": 946125,
  "Tenaglia": 4765286,
  "Ernesto Valverde": 827512,
  "Zubeldia": 973496,
  "Guridi": 827539,
  "Guevara": 827438,
  "Óscar Valentín": 830869,
  "Prados": 827414,
  "El Hilali": 860533,
  "Arda Güler": 104912913,
  "Le Normand": 2668079,
  "Barrenetxea": 32664586,
  "Hugo Alvarez": 828159,
  "Fornals": 145549281,
  "Moncayola": 2703533,
  "Marcelino": 827527,
  "Asencio": 10107144,
  "Morlanes": 827621,
  "Gerard": 50142495,
  "Gayá": 937001,
  "Unai Simón": 4101065,
  "Claudio Giraldez": 827441,
  "Domingos Duarte": 1550420,
  "Camavinga": 22474561,
  "Fermín": 204787954,
  "Iñigo Perez": 827438,
  "Mouriño": 8475417,
  "José Bordalás": 827406,
  "Vesga": 827403,
  "Pol Lozano": 828656,
  "Moi Gómez": 830731,
  "Turrientes": 837974,
  "Gavi": 2779578,
  "Balliu": 827441,
  "Cucho": 54491258,
  "Francés": 827397,
  "Portu": 827418,
  "Iker Muñoz": 827390,
  "Iván Villar": 827387,
  "Edu Expósito": 35605651,
  "F. Garcés": 834188,
  "Aitor Fdez": 827395,
  "Yoel Lago": 827368,
  "Aarón": 11861131,
  "Ez Abde": 127891465,
  "A. Rebbach": 830780,
  "A. Abqar": 830198,
  "Abdón": 827391,
  "A. Mumin": 830318,
  "Abel Ruiz": 827406,
  "Osorio": 846767,
  "Kamara": 827611,
  "Adam B.": 827376,
  "Adama": 827376,
  "Lookman": 31123271,
  "Januzaj": 827497,
  "Dela": 846257,
  "A. Liso": 849544,
  "Adrián Molina": 827366,
  "Adrián": 827349,
  "A. Riquelme": 824853,
  "Aihen": 827435,
  "Aimar Blázquez": 827366,
  "Aimar": 1387896,
  "Fraga": 827512,
  "Mañas": 826638,
  "Paredes": 1233245,
  "Aitor Ruibal": 1021677,
  "Akor": 899630,
  "Alan Matturro": 827627,
  "Alassane": 826082,
  "Albert": 827376,
  "Alberto F.": 827368,
  "A. Moleiro": 85290162,
  "A. Reina": 1101617,
  "Risco": 827368,
  "Febas": 13276945,
  "A. Iturbe": 827369,
  "Mestanza": 825512,
  "Panach": 827201,
  "Rego": 827384,
  "Álex Sancris": 827478,
  "Álex Sánchez": 824936,
  "Puri?": 827673,
  "Andreev": 827412,
  "Alessio Lisci": 827430,
  "Álex Baena": 28144221,
  "Alex Costa": 827369,
  "A. Fores": 827369,
  "Lebarbier": 827348,
  "Alex Marchal": 827283,
  "Alex Moreno": 880496,
  "Padilla": 827413,
  "A. Primo": 827441,
  "Freeman": 845453,
  "Sorloth": 11980128,
  "Alemâo": 827925,
  "Alexis Sánchez": 843841,
  "Alfon": 828622,
  "Pacha": 834955,
  "A. Pedraza": 869917,
  "Nyom": 827414,
  "Arbeloa": 899380,
  "Á. Carreras": 43448999,
  "Fidalgo": 1390771,
  "Álvaro Núñez": 3523519,
  "Odriozola": 827403,
  "Álvaro": 1194903,
  "Á. Valles": 1486877,
  "Gorosabel": 827546,
  "André Silva": 1318208,
  "Christensen": 828781,
  "Ratiu": 70796184,
  "Antañón": 801407,
  "A. Castrín": 827523,
  "Lunin": 2211937,
  "A. Arcos": 826638,
  "A. Fortuño": 848032,
  "Á. Ortiz": 827430,
  "Ángel Pérez": 830421,
  "Budimir": 43191691,
  "Griezmann": 9140448,
  "Toni Lato": 827380,
  "A. Martinez": 827366,
  "Rüdiger": 31077728,
  "Salguero": 827248,
  "Antonio Sánchez": 827397,
  "A. Roca": 827365,
  "Antony": 76473839,
  "Aritz": 827411,
  "Mariezkurrena": 827677,
  "Arnau Tenas": 838227,
  "Danjuma": 2297547,
  "Zakharyan": 827444,
  "Asier Hierro": 827075,
  "A. Osambela": 827362,
  "A. Batalla": 3108936,
  "Witsel": 3455038,
  "Laporte": 7340711,
  "Ayoze": 2360873,
  "Ounahi": 20757052,
  "Santamaría": 829003,
  "Mendy": 832173,
  "Bema Sina": 824936,
  "B. Iglesias": 17049317,
  "B. Mayoral": 859443,
  "Brahim": 4199139,
  "Brais Méndez": 18095168,
  "Bryan Gil": 914977,
  "B. Sangare": 836483,
  "Calebe": 827397,
  "Starfelt": 1366696,
  "Aleñá": 1518247,
  "C. Alvarez": 1471529,
  "Ballestero": 827478,
  "Protesoni": 827414,
  "Carlos Corberán": 827378,
  "C. Dominguez": 827395,
  "C. Espí": 2961962,
  "Carlos Macià": 828194,
  "Carlos Martín": 827386,
  "C. Romero": 24235734,
  "C. Soler": 32595321,
  "Cayetano": 827365,
  "Bakambu": 831400,
  "Azpilicueta": 830030,
  "Palacios": 830606,
  "Pickel": 827450,
  "Ejuke": 834454
};
const MARKET_INFO = {
  "Pedri": {
    "position": "MD",
    "points": 198,
    "value": 209027708
  },
  "Remiro": {
    "position": "PT",
    "points": 181,
    "value": 2655632
  },
  "Iñaki Williams": {
    "position": "DL",
    "points": 178,
    "value": 4527348
  },
  "David Soria": {
    "position": "PT",
    "points": 176,
    "value": 4604393
  },
  "Berenguer": {
    "position": "DL",
    "points": 172,
    "value": 6240258
  },
  "Raíllo": {
    "position": "DF",
    "points": 164,
    "value": 1063271
  },
  "Sergio Herrera": {
    "position": "PT",
    "points": 161,
    "value": 4265349
  },
  "Sergio Gómez": {
    "position": "DF",
    "points": 160,
    "value": 11593047
  },
  "Courtois": {
    "position": "PT",
    "points": 157,
    "value": 17328538
  },
  "Lejeune": {
    "position": "DF",
    "points": 149,
    "value": 70270515
  },
  "Kubo": {
    "position": "MD",
    "points": 147,
    "value": 14320844
  },
  "Pau Cubarsí": {
    "position": "DF",
    "points": 142,
    "value": 71948476
  },
  "Rubén García": {
    "position": "MD",
    "points": 142,
    "value": 20256134
  },
  "Darder": {
    "position": "MD",
    "points": 141,
    "value": 14699931
  },
  "Diego López": {
    "position": "DL",
    "points": 139,
    "value": 874552
  },
  "Álvaro García": {
    "position": "MD",
    "points": 135,
    "value": 8508608
  },
  "Rioja": {
    "position": "MD",
    "points": 135,
    "value": 10104258
  },
  "Arambarri": {
    "position": "MD",
    "points": 133,
    "value": 73215761
  },
  "Marcos Llorente": {
    "position": "DF",
    "points": 130,
    "value": 44864065
  },
  "De Frutos": {
    "position": "DL",
    "points": 129,
    "value": 26025023
  },
  "Kumbulla": {
    "position": "DF",
    "points": 127,
    "value": 827471
  },
  "Marcos Alonso": {
    "position": "DF",
    "points": 125,
    "value": 67367643
  },
  "Cardona": {
    "position": "DF",
    "points": 124,
    "value": 1888786
  },
  "Álex Balde": {
    "position": "DF",
    "points": 121,
    "value": 16995975
  },
  "Giuliano": {
    "position": "DL",
    "points": 121,
    "value": 36641530
  },
  "Boyomo": {
    "position": "DF",
    "points": 120,
    "value": 2934469
  },
  "Tchouaméni": {
    "position": "MD",
    "points": 119,
    "value": 72074886
  },
  "Valjent": {
    "position": "DF",
    "points": 115,
    "value": 1137419
  },
  "Tárrega": {
    "position": "DF",
    "points": 114,
    "value": 1258968
  },
  "Carmona": {
    "position": "DF",
    "points": 114,
    "value": 994622
  },
  "Jofre": {
    "position": "DL",
    "points": 113,
    "value": 827402
  },
  "Yeray": {
    "position": "DF",
    "points": 113,
    "value": 2053802
  },
  "Comesaña": {
    "position": "MD",
    "points": 111,
    "value": 67320974
  },
  "Catena": {
    "position": "DF",
    "points": 110,
    "value": 38121072
  },
  "Guruzeta": {
    "position": "DL",
    "points": 109,
    "value": 2094277
  },
  "Parejo": {
    "position": "MD",
    "points": 106,
    "value": 841392
  },
  "Barrios": {
    "position": "MD",
    "points": 106,
    "value": 17518897
  },
  "Sow": {
    "position": "MD",
    "points": 105,
    "value": 946698
  },
  "Juan Iglesias": {
    "position": "DF",
    "points": 105,
    "value": 1472464
  },
  "Jauregizar": {
    "position": "MD",
    "points": 105,
    "value": 10089237
  },
  "Torró": {
    "position": "MD",
    "points": 103,
    "value": 830612
  },
  "Hansi Flick": {
    "position": "UNK",
    "points": 101,
    "value": 827919
  },
  "Arnau": {
    "position": "DF",
    "points": 100,
    "value": 2462886
  },
  "Yuri": {
    "position": "DF",
    "points": 100,
    "value": 13433557
  },
  "Daley Blind": {
    "position": "DF",
    "points": 99,
    "value": 4294886
  },
  "Iván Martín": {
    "position": "MD",
    "points": 98,
    "value": 1524418
  },
  "Samu Costa": {
    "position": "MD",
    "points": 97,
    "value": 1582683
  },
  "Fran Beltrán": {
    "position": "MD",
    "points": 96,
    "value": 832328
  },
  "Pedrosa": {
    "position": "DF",
    "points": 95,
    "value": 827403
  },
  "David López": {
    "position": "DF",
    "points": 95,
    "value": 827711
  },
  "Javi Rodríguez": {
    "position": "DF",
    "points": 95,
    "value": 829987
  },
  "Almeida": {
    "position": "MD",
    "points": 94,
    "value": 830324
  },
  "De Galarreta": {
    "position": "MD",
    "points": 94,
    "value": 6414871
  },
  "Abel Bretones": {
    "position": "DF",
    "points": 93,
    "value": 830125
  },
  "Hugo Duro": {
    "position": "DL",
    "points": 93,
    "value": 1109998
  },
  "Chavarría": {
    "position": "DF",
    "points": 93,
    "value": 7051390
  },
  "Juanlu": {
    "position": "MD",
    "points": 93,
    "value": 830347
  },
  "Bartra": {
    "position": "DF",
    "points": 93,
    "value": 14357073
  },
  "Altimira": {
    "position": "MD",
    "points": 93,
    "value": 839619
  },
  "Tsygankov": {
    "position": "DL",
    "points": 93,
    "value": 5428604
  },
  "Blanco": {
    "position": "MD",
    "points": 92,
    "value": 1283641
  },
  "Agirrezabala": {
    "position": "PT",
    "points": 92,
    "value": 917280
  },
  "Sivera": {
    "position": "PT",
    "points": 90,
    "value": 946125
  },
  "Tenaglia": {
    "position": "DF",
    "points": 89,
    "value": 4765286
  },
  "Ernesto Valverde": {
    "position": "UNK",
    "points": 88,
    "value": 827512
  },
  "Zubeldia": {
    "position": "DF",
    "points": 88,
    "value": 973496
  },
  "Guridi": {
    "position": "MD",
    "points": 88,
    "value": 827539
  },
  "Guevara": {
    "position": "MD",
    "points": 85,
    "value": 827438
  },
  "Óscar Valentín": {
    "position": "MD",
    "points": 85,
    "value": 830869
  },
  "Prados": {
    "position": "MD",
    "points": 84,
    "value": 827414
  },
  "El Hilali": {
    "position": "DF",
    "points": 84,
    "value": 860533
  },
  "Arda Güler": {
    "position": "MD",
    "points": 83,
    "value": 104912913
  },
  "Le Normand": {
    "position": "DF",
    "points": 83,
    "value": 2668079
  },
  "Barrenetxea": {
    "position": "MD",
    "points": 80,
    "value": 32664586
  },
  "Hugo Alvarez": {
    "position": "MD",
    "points": 80,
    "value": 828159
  },
  "Fornals": {
    "position": "MD",
    "points": 80,
    "value": 145549281
  },
  "Moncayola": {
    "position": "MD",
    "points": 78,
    "value": 2703533
  },
  "Marcelino": {
    "position": "UNK",
    "points": 76,
    "value": 827527
  },
  "Asencio": {
    "position": "DF",
    "points": 73,
    "value": 10107144
  },
  "Morlanes": {
    "position": "MD",
    "points": 72,
    "value": 827621
  },
  "Gerard": {
    "position": "DL",
    "points": 71,
    "value": 50142495
  },
  "Gayá": {
    "position": "DF",
    "points": 70,
    "value": 937001
  },
  "Unai Simón": {
    "position": "PT",
    "points": 69,
    "value": 4101065
  },
  "Claudio Giraldez": {
    "position": "UNK",
    "points": 67,
    "value": 827441
  },
  "Domingos Duarte": {
    "position": "DF",
    "points": 66,
    "value": 1550420
  },
  "Camavinga": {
    "position": "MD",
    "points": 66,
    "value": 22474561
  },
  "Fermín": {
    "position": "MD",
    "points": 65,
    "value": 204787954
  },
  "Iñigo Perez": {
    "position": "UNK",
    "points": 65,
    "value": 827438
  },
  "Mouriño": {
    "position": "DF",
    "points": 65,
    "value": 8475417
  },
  "José Bordalás": {
    "position": "UNK",
    "points": 61,
    "value": 827406
  },
  "Vesga": {
    "position": "MD",
    "points": 55,
    "value": 827403
  },
  "Pol Lozano": {
    "position": "MD",
    "points": 53,
    "value": 828656
  },
  "Moi Gómez": {
    "position": "MD",
    "points": 48,
    "value": 830731
  },
  "Turrientes": {
    "position": "MD",
    "points": 47,
    "value": 837974
  },
  "Gavi": {
    "position": "MD",
    "points": 36,
    "value": 2779578
  },
  "Balliu": {
    "position": "DF",
    "points": 35,
    "value": 827441
  },
  "Cucho": {
    "position": "DL",
    "points": 33,
    "value": 54491258
  },
  "Francés": {
    "position": "DF",
    "points": 32,
    "value": 827397
  },
  "Portu": {
    "position": "DL",
    "points": 29,
    "value": 827418
  },
  "Iker Muñoz": {
    "position": "MD",
    "points": 24,
    "value": 827390
  },
  "Iván Villar": {
    "position": "PT",
    "points": 22,
    "value": 827387
  },
  "Edu Expósito": {
    "position": "MD",
    "points": 11,
    "value": 35605651
  },
  "F. Garcés": {
    "position": "DF",
    "points": 2,
    "value": 834188
  },
  "Aitor Fdez": {
    "position": "PT",
    "points": 0,
    "value": 827395
  },
  "Yoel Lago": {
    "position": "DF",
    "points": 0,
    "value": 827368
  },
  "Aarón": {
    "position": "PT",
    "points": 0,
    "value": 11861131
  },
  "Ez Abde": {
    "position": "DL",
    "points": 0,
    "value": 127891465
  },
  "A. Rebbach": {
    "position": "DL",
    "points": 0,
    "value": 830780
  },
  "A. Abqar": {
    "position": "DF",
    "points": 0,
    "value": 830198
  },
  "Abdón": {
    "position": "DL",
    "points": 0,
    "value": 827391
  },
  "A. Mumin": {
    "position": "DF",
    "points": 0,
    "value": 830318
  },
  "Abel Ruiz": {
    "position": "DL",
    "points": 0,
    "value": 827406
  },
  "Osorio": {
    "position": "DL",
    "points": 0,
    "value": 846767
  },
  "Kamara": {
    "position": "DL",
    "points": 0,
    "value": 827611
  },
  "Adam B.": {
    "position": "MD",
    "points": 0,
    "value": 827376
  },
  "Adama": {
    "position": "DF",
    "points": 0,
    "value": 827376
  },
  "Lookman": {
    "position": "DL",
    "points": 0,
    "value": 31123271
  },
  "Januzaj": {
    "position": "MD",
    "points": 0,
    "value": 827497
  },
  "Dela": {
    "position": "DF",
    "points": 0,
    "value": 846257
  },
  "A. Liso": {
    "position": "DL",
    "points": 0,
    "value": 849544
  },
  "Adrián Molina": {
    "position": "PT",
    "points": 0,
    "value": 827366
  },
  "Adrián": {
    "position": "DL",
    "points": 0,
    "value": 827349
  },
  "A. Riquelme": {
    "position": "MD",
    "points": 0,
    "value": 824853
  },
  "Aihen": {
    "position": "DF",
    "points": 0,
    "value": 827435
  },
  "Aimar Blázquez": {
    "position": "DL",
    "points": 0,
    "value": 827366
  },
  "Aimar": {
    "position": "MD",
    "points": 0,
    "value": 1387896
  },
  "Fraga": {
    "position": "PT",
    "points": 0,
    "value": 827512
  },
  "Mañas": {
    "position": "DL",
    "points": 0,
    "value": 826638
  },
  "Paredes": {
    "position": "DF",
    "points": 0,
    "value": 1233245
  },
  "Aitor Ruibal": {
    "position": "DL",
    "points": 0,
    "value": 1021677
  },
  "Akor": {
    "position": "DL",
    "points": 0,
    "value": 899630
  },
  "Alan Matturro": {
    "position": "DF",
    "points": 0,
    "value": 827627
  },
  "Alassane": {
    "position": "MD",
    "points": 0,
    "value": 826082
  },
  "Albert": {
    "position": "DF",
    "points": 0,
    "value": 827376
  },
  "Alberto F.": {
    "position": "PT",
    "points": 0,
    "value": 827368
  },
  "A. Moleiro": {
    "position": "MD",
    "points": 0,
    "value": 85290162
  },
  "A. Reina": {
    "position": "MD",
    "points": 0,
    "value": 1101617
  },
  "Risco": {
    "position": "MD",
    "points": 0,
    "value": 827368
  },
  "Febas": {
    "position": "MD",
    "points": 0,
    "value": 13276945
  },
  "A. Iturbe": {
    "position": "PT",
    "points": 0,
    "value": 827369
  },
  "Mestanza": {
    "position": "MD",
    "points": 0,
    "value": 825512
  },
  "Panach": {
    "position": "DF",
    "points": 0,
    "value": 827201
  },
  "Rego": {
    "position": "DF",
    "points": 0,
    "value": 827384
  },
  "Álex Sancris": {
    "position": "DL",
    "points": 0,
    "value": 827478
  },
  "Álex Sánchez": {
    "position": "MD",
    "points": 0,
    "value": 824936
  },
  "Puri?": {
    "position": "DF",
    "points": 0,
    "value": 827673
  },
  "Andreev": {
    "position": "PT",
    "points": 0,
    "value": 827412
  },
  "Alessio Lisci": {
    "position": "UNK",
    "points": 0,
    "value": 827430
  },
  "Álex Baena": {
    "position": "MD",
    "points": 0,
    "value": 28144221
  },
  "Alex Costa": {
    "position": "DL",
    "points": 0,
    "value": 827369
  },
  "A. Fores": {
    "position": "DL",
    "points": 0,
    "value": 827369
  },
  "Lebarbier": {
    "position": "DF",
    "points": 0,
    "value": 827348
  },
  "Alex Marchal": {
    "position": "MD",
    "points": 0,
    "value": 827283
  },
  "Alex Moreno": {
    "position": "DF",
    "points": 0,
    "value": 880496
  },
  "Padilla": {
    "position": "PT",
    "points": 0,
    "value": 827413
  },
  "A. Primo": {
    "position": "PT",
    "points": 0,
    "value": 827441
  },
  "Freeman": {
    "position": "DF",
    "points": 0,
    "value": 845453
  },
  "Sorloth": {
    "position": "DL",
    "points": 0,
    "value": 11980128
  },
  "Alemâo": {
    "position": "DL",
    "points": 0,
    "value": 827925
  },
  "Alexis Sánchez": {
    "position": "DL",
    "points": 0,
    "value": 843841
  },
  "Alfon": {
    "position": "DL",
    "points": 0,
    "value": 828622
  },
  "Pacha": {
    "position": "DF",
    "points": 0,
    "value": 834955
  },
  "A. Pedraza": {
    "position": "DF",
    "points": 0,
    "value": 869917
  },
  "Nyom": {
    "position": "DF",
    "points": 0,
    "value": 827414
  },
  "Arbeloa": {
    "position": "UNK",
    "points": 0,
    "value": 899380
  },
  "Á. Carreras": {
    "position": "DF",
    "points": 0,
    "value": 43448999
  },
  "Fidalgo": {
    "position": "MD",
    "points": 0,
    "value": 1390771
  },
  "Álvaro Núñez": {
    "position": "DF",
    "points": 0,
    "value": 3523519
  },
  "Odriozola": {
    "position": "DF",
    "points": 0,
    "value": 827403
  },
  "Álvaro": {
    "position": "DL",
    "points": 0,
    "value": 1194903
  },
  "Á. Valles": {
    "position": "PT",
    "points": 0,
    "value": 1486877
  },
  "Gorosabel": {
    "position": "DF",
    "points": 0,
    "value": 827546
  },
  "André Silva": {
    "position": "DL",
    "points": 0,
    "value": 1318208
  },
  "Christensen": {
    "position": "DF",
    "points": 0,
    "value": 828781
  },
  "Ratiu": {
    "position": "DF",
    "points": 0,
    "value": 70796184
  },
  "Antañón": {
    "position": "MD",
    "points": 0,
    "value": 801407
  },
  "A. Castrín": {
    "position": "DF",
    "points": 0,
    "value": 827523
  },
  "Lunin": {
    "position": "PT",
    "points": 0,
    "value": 2211937
  },
  "A. Arcos": {
    "position": "MD",
    "points": 0,
    "value": 826638
  },
  "A. Fortuño": {
    "position": "PT",
    "points": 0,
    "value": 848032
  },
  "Á. Ortiz": {
    "position": "DF",
    "points": 0,
    "value": 827430
  },
  "Ángel Pérez": {
    "position": "DL",
    "points": 0,
    "value": 830421
  },
  "Budimir": {
    "position": "DL",
    "points": 0,
    "value": 43191691
  },
  "Griezmann": {
    "position": "DL",
    "points": 0,
    "value": 9140448
  },
  "Toni Lato": {
    "position": "DF",
    "points": 0,
    "value": 827380
  },
  "A. Martinez": {
    "position": "MD",
    "points": 0,
    "value": 827366
  },
  "Rüdiger": {
    "position": "DF",
    "points": 0,
    "value": 31077728
  },
  "Salguero": {
    "position": "DF",
    "points": 0,
    "value": 827248
  },
  "Antonio Sánchez": {
    "position": "MD",
    "points": 0,
    "value": 827397
  },
  "A. Roca": {
    "position": "MD",
    "points": 0,
    "value": 827365
  },
  "Antony": {
    "position": "DL",
    "points": 0,
    "value": 76473839
  },
  "Aritz": {
    "position": "DF",
    "points": 0,
    "value": 827411
  },
  "Mariezkurrena": {
    "position": "DL",
    "points": 0,
    "value": 827677
  },
  "Arnau Tenas": {
    "position": "PT",
    "points": 0,
    "value": 838227
  },
  "Danjuma": {
    "position": "DL",
    "points": 0,
    "value": 2297547
  },
  "Zakharyan": {
    "position": "MD",
    "points": 0,
    "value": 827444
  },
  "Asier Hierro": {
    "position": "DL",
    "points": 0,
    "value": 827075
  },
  "A. Osambela": {
    "position": "MD",
    "points": 0,
    "value": 827362
  },
  "A. Batalla": {
    "position": "PT",
    "points": 0,
    "value": 3108936
  },
  "Witsel": {
    "position": "MD",
    "points": 0,
    "value": 3455038
  },
  "Laporte": {
    "position": "DF",
    "points": 0,
    "value": 7340711
  },
  "Ayoze": {
    "position": "DL",
    "points": 0,
    "value": 2360873
  },
  "Ounahi": {
    "position": "MD",
    "points": 0,
    "value": 20757052
  },
  "Santamaría": {
    "position": "MD",
    "points": 0,
    "value": 829003
  },
  "Mendy": {
    "position": "MD",
    "points": 0,
    "value": 832173
  },
  "Bema Sina": {
    "position": "DF",
    "points": 0,
    "value": 824936
  },
  "B. Iglesias": {
    "position": "DL",
    "points": 0,
    "value": 17049317
  },
  "B. Mayoral": {
    "position": "DL",
    "points": 0,
    "value": 859443
  },
  "Brahim": {
    "position": "MD",
    "points": 0,
    "value": 4199139
  },
  "Brais Méndez": {
    "position": "MD",
    "points": 0,
    "value": 18095168
  },
  "Bryan Gil": {
    "position": "DL",
    "points": 0,
    "value": 914977
  },
  "B. Sangare": {
    "position": "DF",
    "points": 0,
    "value": 836483
  },
  "Calebe": {
    "position": "MD",
    "points": 0,
    "value": 827397
  },
  "Starfelt": {
    "position": "DF",
    "points": 0,
    "value": 1366696
  },
  "Aleñá": {
    "position": "MD",
    "points": 0,
    "value": 1518247
  },
  "C. Alvarez": {
    "position": "MD",
    "points": 0,
    "value": 1471529
  },
  "Ballestero": {
    "position": "DF",
    "points": 0,
    "value": 827478
  },
  "Protesoni": {
    "position": "MD",
    "points": 0,
    "value": 827414
  },
  "Carlos Corberán": {
    "position": "UNK",
    "points": 0,
    "value": 827378
  },
  "C. Dominguez": {
    "position": "DF",
    "points": 0,
    "value": 827395
  },
  "C. Espí": {
    "position": "DL",
    "points": 0,
    "value": 2961962
  },
  "Carlos Macià": {
    "position": "MD",
    "points": 0,
    "value": 828194
  },
  "Carlos Martín": {
    "position": "MD",
    "points": 0,
    "value": 827386
  },
  "C. Romero": {
    "position": "DF",
    "points": 0,
    "value": 24235734
  },
  "C. Soler": {
    "position": "MD",
    "points": 0,
    "value": 32595321
  },
  "Cayetano": {
    "position": "PT",
    "points": 0,
    "value": 827365
  },
  "Bakambu": {
    "position": "DL",
    "points": 0,
    "value": 831400
  },
  "Azpilicueta": {
    "position": "DF",
    "points": 0,
    "value": 830030
  },
  "Palacios": {
    "position": "MD",
    "points": 0,
    "value": 830606
  },
  "Pickel": {
    "position": "MD",
    "points": 0,
    "value": 827450
  },
  "Ejuke": {
    "position": "DL",
    "points": 0,
    "value": 834454
  }
};
const MARKET_TRENDS = {
  "Pedri": {
    "trend": -573442,
    "trendPct": -0.27
  },
  "Remiro": {
    "trend": -40223,
    "trendPct": -1.49
  },
  "Iñaki Williams": {
    "trend": -63587,
    "trendPct": -1.39
  },
  "David Soria": {
    "trend": -29928,
    "trendPct": -0.65
  },
  "Berenguer": {
    "trend": -118115,
    "trendPct": -1.86
  },
  "Raíllo": {
    "trend": -8671,
    "trendPct": -0.81
  },
  "Sergio Herrera": {
    "trend": -53072,
    "trendPct": -1.23
  },
  "Sergio Gómez": {
    "trend": 45633,
    "trendPct": 0.4
  },
  "Courtois": {
    "trend": 46773,
    "trendPct": 0.27
  },
  "Lejeune": {
    "trend": 1092684,
    "trendPct": 1.58
  },
  "Kubo": {
    "trend": -123029,
    "trendPct": -0.85
  },
  "Pau Cubarsí": {
    "trend": 110715,
    "trendPct": 0.15
  },
  "Rubén García": {
    "trend": -15751,
    "trendPct": -0.08
  },
  "Darder": {
    "trend": 171764,
    "trendPct": 1.18
  },
  "Diego López": {
    "trend": -808,
    "trendPct": -0.09
  },
  "Álvaro García": {
    "trend": -193972,
    "trendPct": -2.23
  },
  "Rioja": {
    "trend": -145830,
    "trendPct": -1.42
  },
  "Arambarri": {
    "trend": -392731,
    "trendPct": -0.53
  },
  "Marcos Llorente": {
    "trend": -316707,
    "trendPct": -0.7
  },
  "De Frutos": {
    "trend": -87440,
    "trendPct": -0.33
  },
  "Kumbulla": {
    "trend": 1154,
    "trendPct": 0.14
  },
  "Marcos Alonso": {
    "trend": -524174,
    "trendPct": -0.77
  },
  "Cardona": {
    "trend": -4282,
    "trendPct": -0.23
  },
  "Álex Balde": {
    "trend": -311936,
    "trendPct": -1.8
  },
  "Giuliano": {
    "trend": -371012,
    "trendPct": -1.0
  },
  "Boyomo": {
    "trend": -5210,
    "trendPct": -0.18
  },
  "Tchouaméni": {
    "trend": -184853,
    "trendPct": -0.26
  },
  "Valjent": {
    "trend": 11775,
    "trendPct": 1.05
  },
  "Tárrega": {
    "trend": -16088,
    "trendPct": -1.26
  },
  "Carmona": {
    "trend": -5810,
    "trendPct": -0.58
  },
  "Jofre": {
    "trend": 1157,
    "trendPct": 0.14
  },
  "Yeray": {
    "trend": -32676,
    "trendPct": -1.57
  },
  "Comesaña": {
    "trend": 880436,
    "trendPct": 1.33
  },
  "Catena": {
    "trend": 267154,
    "trendPct": 0.71
  },
  "Guruzeta": {
    "trend": 78635,
    "trendPct": 3.9
  },
  "Parejo": {
    "trend": 574,
    "trendPct": 0.07
  },
  "Barrios": {
    "trend": -400370,
    "trendPct": -2.23
  },
  "Sow": {
    "trend": -3814,
    "trendPct": -0.4
  },
  "Juan Iglesias": {
    "trend": -21894,
    "trendPct": -1.47
  },
  "Jauregizar": {
    "trend": -148860,
    "trendPct": -1.45
  },
  "Torró": {
    "trend": 1023,
    "trendPct": 0.12
  },
  "Hansi Flick": {
    "trend": 1135,
    "trendPct": 0.14
  },
  "Arnau": {
    "trend": -24406,
    "trendPct": -0.98
  },
  "Yuri": {
    "trend": 109720,
    "trendPct": 0.82
  },
  "Daley Blind": {
    "trend": -55975,
    "trendPct": -1.29
  },
  "Iván Martín": {
    "trend": -26345,
    "trendPct": -1.7
  },
  "Samu Costa": {
    "trend": 58897,
    "trendPct": 3.87
  },
  "Fran Beltrán": {
    "trend": 952,
    "trendPct": 0.11
  },
  "Pedrosa": {
    "trend": 1157,
    "trendPct": 0.14
  },
  "David López": {
    "trend": 1144,
    "trendPct": 0.14
  },
  "Javi Rodríguez": {
    "trend": 1049,
    "trendPct": 0.13
  },
  "Almeida": {
    "trend": 1035,
    "trendPct": 0.12
  },
  "De Galarreta": {
    "trend": -7986,
    "trendPct": -0.12
  },
  "Abel Bretones": {
    "trend": 1044,
    "trendPct": 0.13
  },
  "Hugo Duro": {
    "trend": -10618,
    "trendPct": -0.95
  },
  "Chavarría": {
    "trend": -97776,
    "trendPct": -1.37
  },
  "Juanlu": {
    "trend": 1034,
    "trendPct": 0.12
  },
  "Bartra": {
    "trend": -333583,
    "trendPct": -2.27
  },
  "Altimira": {
    "trend": 648,
    "trendPct": 0.08
  },
  "Tsygankov": {
    "trend": -60308,
    "trendPct": -1.1
  },
  "Blanco": {
    "trend": -5486,
    "trendPct": -0.43
  },
  "Agirrezabala": {
    "trend": -2588,
    "trendPct": -0.28
  },
  "Sivera": {
    "trend": -3790,
    "trendPct": -0.4
  },
  "Tenaglia": {
    "trend": -17592,
    "trendPct": -0.37
  },
  "Ernesto Valverde": {
    "trend": 1152,
    "trendPct": 0.14
  },
  "Zubeldia": {
    "trend": -4930,
    "trendPct": -0.5
  },
  "Guridi": {
    "trend": 1151,
    "trendPct": 0.14
  },
  "Guevara": {
    "trend": 1155,
    "trendPct": 0.14
  },
  "Óscar Valentín": {
    "trend": 1013,
    "trendPct": 0.12
  },
  "Prados": {
    "trend": 1156,
    "trendPct": 0.14
  },
  "El Hilali": {
    "trend": -223,
    "trendPct": -0.03
  },
  "Arda Güler": {
    "trend": -2421578,
    "trendPct": -2.26
  },
  "Le Normand": {
    "trend": 20169,
    "trendPct": 0.76
  },
  "Barrenetxea": {
    "trend": 149144,
    "trendPct": 0.46
  },
  "Hugo Alvarez": {
    "trend": 1125,
    "trendPct": 0.14
  },
  "Fornals": {
    "trend": 590319,
    "trendPct": 0.41
  },
  "Moncayola": {
    "trend": -17396,
    "trendPct": -0.64
  },
  "Marcelino": {
    "trend": 1152,
    "trendPct": 0.14
  },
  "Asencio": {
    "trend": -219811,
    "trendPct": -2.13
  },
  "Morlanes": {
    "trend": 1148,
    "trendPct": 0.14
  },
  "Gerard": {
    "trend": -135200,
    "trendPct": -0.27
  },
  "Gayá": {
    "trend": 6923,
    "trendPct": 0.74
  },
  "Unai Simón": {
    "trend": -42673,
    "trendPct": -1.03
  },
  "Claudio Giraldez": {
    "trend": 1155,
    "trendPct": 0.14
  },
  "Domingos Duarte": {
    "trend": -16847,
    "trendPct": -1.07
  },
  "Camavinga": {
    "trend": -450271,
    "trendPct": -1.96
  },
  "Fermín": {
    "trend": 1061500,
    "trendPct": 0.52
  },
  "Iñigo Perez": {
    "trend": 1155,
    "trendPct": 0.14
  },
  "Mouriño": {
    "trend": -157989,
    "trendPct": -1.83
  },
  "José Bordalás": {
    "trend": 1157,
    "trendPct": 0.14
  },
  "Vesga": {
    "trend": 1157,
    "trendPct": 0.14
  },
  "Pol Lozano": {
    "trend": 1105,
    "trendPct": 0.13
  },
  "Moi Gómez": {
    "trend": 1018,
    "trendPct": 0.12
  },
  "Turrientes": {
    "trend": 716,
    "trendPct": 0.09
  },
  "Gavi": {
    "trend": 39766,
    "trendPct": 1.45
  },
  "Balliu": {
    "trend": 1155,
    "trendPct": 0.14
  },
  "Cucho": {
    "trend": 1257924,
    "trendPct": 2.36
  },
  "Francés": {
    "trend": 1157,
    "trendPct": 0.14
  },
  "Portu": {
    "trend": 1156,
    "trendPct": 0.14
  },
  "Iker Muñoz": {
    "trend": 1157,
    "trendPct": 0.14
  },
  "Iván Villar": {
    "trend": 1158,
    "trendPct": 0.14
  },
  "Edu Expósito": {
    "trend": 462878,
    "trendPct": 1.32
  },
  "F. Garcés": {
    "trend": 874,
    "trendPct": 0.1
  },
  "Aitor Fdez": {
    "trend": 1157,
    "trendPct": 0.14
  },
  "Yoel Lago": {
    "trend": 1158,
    "trendPct": 0.14
  },
  "Aarón": {
    "trend": -132317,
    "trendPct": -1.1
  },
  "Ez Abde": {
    "trend": 2303039,
    "trendPct": 1.83
  },
  "A. Rebbach": {
    "trend": 1016,
    "trendPct": 0.12
  },
  "A. Abqar": {
    "trend": 1041,
    "trendPct": 0.13
  },
  "Abdón": {
    "trend": 1157,
    "trendPct": 0.14
  },
  "A. Mumin": {
    "trend": 1035,
    "trendPct": 0.12
  },
  "Abel Ruiz": {
    "trend": 1157,
    "trendPct": 0.14
  },
  "Osorio": {
    "trend": 350,
    "trendPct": 0.04
  },
  "Kamara": {
    "trend": 1148,
    "trendPct": 0.14
  },
  "Adam B.": {
    "trend": 1158,
    "trendPct": 0.14
  },
  "Adama": {
    "trend": 1158,
    "trendPct": 0.14
  },
  "Lookman": {
    "trend": -332058,
    "trendPct": -1.06
  },
  "Januzaj": {
    "trend": 1153,
    "trendPct": 0.14
  },
  "Dela": {
    "trend": 371,
    "trendPct": 0.04
  },
  "A. Liso": {
    "trend": 234,
    "trendPct": 0.03
  },
  "Adrián Molina": {
    "trend": 1159,
    "trendPct": 0.14
  },
  "Adrián": {
    "trend": 1159,
    "trendPct": 0.14
  },
  "A. Riquelme": {
    "trend": 1263,
    "trendPct": 0.15
  },
  "Aihen": {
    "trend": 1156,
    "trendPct": 0.14
  },
  "Aimar Blázquez": {
    "trend": 1159,
    "trendPct": 0.14
  },
  "Aimar": {
    "trend": -22197,
    "trendPct": -1.57
  },
  "Fraga": {
    "trend": 1152,
    "trendPct": 0.14
  },
  "Mañas": {
    "trend": 1189,
    "trendPct": 0.14
  },
  "Paredes": {
    "trend": -15753,
    "trendPct": -1.26
  },
  "Aitor Ruibal": {
    "trend": -6938,
    "trendPct": -0.67
  },
  "Akor": {
    "trend": -1853,
    "trendPct": -0.21
  },
  "Alan Matturro": {
    "trend": 1148,
    "trendPct": 0.14
  },
  "Alassane": {
    "trend": 1212,
    "trendPct": 0.15
  },
  "Albert": {
    "trend": 1158,
    "trendPct": 0.14
  },
  "Alberto F.": {
    "trend": 1158,
    "trendPct": 0.14
  },
  "A. Moleiro": {
    "trend": 1621880,
    "trendPct": 1.94
  },
  "A. Reina": {
    "trend": 906,
    "trendPct": 0.08
  },
  "Risco": {
    "trend": 1158,
    "trendPct": 0.14
  },
  "Febas": {
    "trend": 13843,
    "trendPct": 0.1
  },
  "A. Iturbe": {
    "trend": 1158,
    "trendPct": 0.14
  },
  "Mestanza": {
    "trend": 1236,
    "trendPct": 0.15
  },
  "Panach": {
    "trend": 1165,
    "trendPct": 0.14
  },
  "Rego": {
    "trend": 1158,
    "trendPct": 0.14
  },
  "Álex Sancris": {
    "trend": 1154,
    "trendPct": 0.14
  },
  "Álex Sánchez": {
    "trend": 1260,
    "trendPct": 0.15
  },
  "Puri?": {
    "trend": 1146,
    "trendPct": 0.14
  },
  "Andreev": {
    "trend": 1157,
    "trendPct": 0.14
  },
  "Alessio Lisci": {
    "trend": 1156,
    "trendPct": 0.14
  },
  "Álex Baena": {
    "trend": -205876,
    "trendPct": -0.73
  },
  "Alex Costa": {
    "trend": 1158,
    "trendPct": 0.14
  },
  "A. Fores": {
    "trend": 1158,
    "trendPct": 0.14
  },
  "Lebarbier": {
    "trend": 1159,
    "trendPct": 0.14
  },
  "Alex Marchal": {
    "trend": 1162,
    "trendPct": 0.14
  },
  "Alex Moreno": {
    "trend": -1055,
    "trendPct": -0.12
  },
  "Padilla": {
    "trend": 1157,
    "trendPct": 0.14
  },
  "A. Primo": {
    "trend": 1155,
    "trendPct": 0.14
  },
  "Freeman": {
    "trend": 405,
    "trendPct": 0.05
  },
  "Sorloth": {
    "trend": -24410,
    "trendPct": -0.2
  },
  "Alemâo": {
    "trend": 1135,
    "trendPct": 0.14
  },
  "Alexis Sánchez": {
    "trend": 472,
    "trendPct": 0.06
  },
  "Alfon": {
    "trend": 1106,
    "trendPct": 0.13
  },
  "Pacha": {
    "trend": 842,
    "trendPct": 0.1
  },
  "A. Pedraza": {
    "trend": -614,
    "trendPct": -0.07
  },
  "Nyom": {
    "trend": 1156,
    "trendPct": 0.14
  },
  "Arbeloa": {
    "trend": -1842,
    "trendPct": -0.2
  },
  "Á. Carreras": {
    "trend": -814711,
    "trendPct": -1.84
  },
  "Fidalgo": {
    "trend": -22317,
    "trendPct": -1.58
  },
  "Álvaro Núñez": {
    "trend": -49380,
    "trendPct": -1.38
  },
  "Odriozola": {
    "trend": 1157,
    "trendPct": 0.14
  },
  "Álvaro": {
    "trend": -14156,
    "trendPct": -1.17
  },
  "Á. Valles": {
    "trend": -1171,
    "trendPct": -0.08
  },
  "Gorosabel": {
    "trend": 1151,
    "trendPct": 0.14
  },
  "André Silva": {
    "trend": 39414,
    "trendPct": 3.08
  },
  "Christensen": {
    "trend": 1100,
    "trendPct": 0.13
  },
  "Ratiu": {
    "trend": -847035,
    "trendPct": -1.18
  },
  "Antañón": {
    "trend": 2240,
    "trendPct": 0.28
  },
  "A. Castrín": {
    "trend": 1152,
    "trendPct": 0.14
  },
  "Lunin": {
    "trend": -14602,
    "trendPct": -0.66
  },
  "A. Arcos": {
    "trend": 1189,
    "trendPct": 0.14
  },
  "A. Fortuño": {
    "trend": 297,
    "trendPct": 0.04
  },
  "Á. Ortiz": {
    "trend": 1156,
    "trendPct": 0.14
  },
  "Ángel Pérez": {
    "trend": 1031,
    "trendPct": 0.12
  },
  "Budimir": {
    "trend": -70269,
    "trendPct": -0.16
  },
  "Griezmann": {
    "trend": 111458,
    "trendPct": 1.23
  },
  "Toni Lato": {
    "trend": 1158,
    "trendPct": 0.14
  },
  "A. Martinez": {
    "trend": 1159,
    "trendPct": 0.14
  },
  "Rüdiger": {
    "trend": -103979,
    "trendPct": -0.33
  },
  "Salguero": {
    "trend": 1163,
    "trendPct": 0.14
  },
  "Antonio Sánchez": {
    "trend": 1157,
    "trendPct": 0.14
  },
  "A. Roca": {
    "trend": 1159,
    "trendPct": 0.14
  },
  "Antony": {
    "trend": 1260924,
    "trendPct": 1.68
  },
  "Aritz": {
    "trend": 1157,
    "trendPct": 0.14
  },
  "Mariezkurrena": {
    "trend": 1146,
    "trendPct": 0.14
  },
  "Arnau Tenas": {
    "trend": 706,
    "trendPct": 0.08
  },
  "Danjuma": {
    "trend": -42972,
    "trendPct": -1.84
  },
  "Zakharyan": {
    "trend": 1155,
    "trendPct": 0.14
  },
  "Asier Hierro": {
    "trend": 1171,
    "trendPct": 0.14
  },
  "A. Osambela": {
    "trend": 1159,
    "trendPct": 0.14
  },
  "A. Batalla": {
    "trend": -26593,
    "trendPct": -0.85
  },
  "Witsel": {
    "trend": -23530,
    "trendPct": -0.68
  },
  "Laporte": {
    "trend": -76628,
    "trendPct": -1.03
  },
  "Ayoze": {
    "trend": -44763,
    "trendPct": -1.86
  },
  "Ounahi": {
    "trend": -26674,
    "trendPct": -0.13
  },
  "Santamaría": {
    "trend": 1090,
    "trendPct": 0.13
  },
  "Mendy": {
    "trend": 958,
    "trendPct": 0.12
  },
  "Bema Sina": {
    "trend": 1260,
    "trendPct": 0.15
  },
  "B. Iglesias": {
    "trend": -2386,
    "trendPct": -0.01
  },
  "B. Mayoral": {
    "trend": -178,
    "trendPct": -0.02
  },
  "Brahim": {
    "trend": -26689,
    "trendPct": -0.63
  },
  "Brais Méndez": {
    "trend": -363782,
    "trendPct": -1.97
  },
  "Bryan Gil": {
    "trend": -2492,
    "trendPct": -0.27
  },
  "B. Sangare": {
    "trend": 779,
    "trendPct": 0.09
  },
  "Calebe": {
    "trend": 1157,
    "trendPct": 0.14
  },
  "Starfelt": {
    "trend": -21314,
    "trendPct": -1.54
  },
  "Aleñá": {
    "trend": -27628,
    "trendPct": -1.79
  },
  "C. Alvarez": {
    "trend": -25682,
    "trendPct": -1.72
  },
  "Ballestero": {
    "trend": 1154,
    "trendPct": 0.14
  },
  "Protesoni": {
    "trend": 1156,
    "trendPct": 0.14
  },
  "Carlos Corberán": {
    "trend": 1158,
    "trendPct": 0.14
  },
  "C. Dominguez": {
    "trend": 1157,
    "trendPct": 0.14
  },
  "C. Espí": {
    "trend": 27344,
    "trendPct": 0.93
  },
  "Carlos Macià": {
    "trend": 1124,
    "trendPct": 0.14
  },
  "Carlos Martín": {
    "trend": 1158,
    "trendPct": 0.14
  },
  "C. Romero": {
    "trend": -193076,
    "trendPct": -0.79
  },
  "C. Soler": {
    "trend": -264313,
    "trendPct": -0.8
  },
  "Cayetano": {
    "trend": 1159,
    "trendPct": 0.14
  },
  "Bakambu": {
    "trend": 990,
    "trendPct": 0.12
  },
  "Azpilicueta": {
    "trend": 1048,
    "trendPct": 0.13
  },
  "Palacios": {
    "trend": 1024,
    "trendPct": 0.12
  },
  "Pickel": {
    "trend": 1155,
    "trendPct": 0.14
  },
  "Ejuke": {
    "trend": 7414,
    "trendPct": 0.9
  }
};
