// Auto-generated by scrape_market.py from guiafantasy.com
// Generated: 2026-02-08 08:04
// Total Players: 205
const MARKET_DATA = {
  "Pedri": 114816160,
  "Remiro": 4997018,
  "Iñaki Williams": 5840963,
  "David Soria": 5352956,
  "Berenguer": 18600787,
  "Raíllo": 3678098,
  "Sergio Herrera": 10486804,
  "Sergio Gómez": 6480668,
  "Courtois": 51108378,
  "Lejeune": 40779432,
  "Kubo": 20461869,
  "Pau Cubarsí": 45819605,
  "Rubén García": 17021971,
  "Darder": 12406771,
  "Diego López": 2215499,
  "Álvaro García": 17831775,
  "Rioja": 9497816,
  "Arambarri": 20759081,
  "Marcos Llorente": 87555877,
  "De Frutos": 41308470,
  "Kumbulla": 596556,
  "Marcos Alonso": 45136876,
  "Cardona": 5161397,
  "Álex Balde": 47120138,
  "Giuliano": 53275470,
  "Boyomo": 8588013,
  "Tchouaméni": 62413764,
  "Valjent": 2296961,
  "Tárrega": 3400314,
  "Carmona": 4405914,
  "Jofre": 594056,
  "Comesaña": 23173230,
  "Catena": 36119042,
  "Guruzeta": 1239495,
  "Parejo": 876612,
  "Barrios": 66720660,
  "Sow": 604627,
  "Juan Iglesias": 815907,
  "Jauregizar": 24134275,
  "Torró": 697946,
  "Hansi Flick": 612871,
  "Arnau": 1635760,
  "Yuri": 8030741,
  "Daley Blind": 2632369,
  "Iván Martín": 3134591,
  "Samu Costa": 1319450,
  "Fran Beltrán": 625653,
  "Pedrosa": 594143,
  "David López": 605301,
  "Javi Rodríguez": 658404,
  "Almeida": 700218,
  "De Galarreta": 5646959,
  "Abel Bretones": 692973,
  "Hugo Duro": 3420567,
  "Chavarría": 12615608,
  "Juanlu": 701039,
  "Bartra": 42290521,
  "Altimira": 1008155,
  "Tsygankov": 6742194,
  "Blanco": 2548413,
  "Agirrezabala": 3449846,
  "Sivera": 2470743,
  "Tenaglia": 11456879,
  "Ernesto Valverde": 598107,
  "Zubeldia": 2712144,
  "Guridi": 599140,
  "Guevara": 595330,
  "Óscar Valentín": 719975,
  "Prados": 594620,
  "El Hilali": 1672992,
  "Arda Güler": 111975317,
  "Le Normand": 7837996,
  "Barrenetxea": 27911740,
  "Hugo Alvarez": 621607,
  "Fornals": 130938647,
  "Moncayola": 5564814,
  "Marcelino": 598591,
  "Asencio": 20963391,
  "Morlanes": 602065,
  "Gerard": 49890574,
  "Gayá": 993144,
  "Jagoba Arrasate": 595961,
  "Unai Simón": 9626213,
  "Claudio Giraldez": 595437,
  "Domingos Duarte": 1087829,
  "Camavinga": 32442886,
  "Fermín": 146794063,
  "Iñigo Perez": 595341,
  "Mouriño": 7227257,
  "José Bordalás": 594234,
  "Vesga": 594128,
  "Pol Lozano": 639605,
  "Moi Gómez": 714990,
  "Turrientes": 607348,
  "Gavi": 668836,
  "Balliu": 595528,
  "Cucho": 60344339,
  "Francés": 593906,
  "Portu": 594699,
  "Iker Muñoz": 593701,
  "Iván Villar": 593545,
  "Edu Expósito": 77929265,
  "F. Garcés": 712989,
  "Ramón Martínez": 592620,
  "Aitor Fdez": 593795,
  "Yoel Lago": 592905,
  "Aarón": 21226077,
  "Ez Abde": 55263579,
  "A. Rebbach": 593447,
  "A. Abqar": 695568,
  "Abdón": 593729,
  "A. Mumin": 593379,
  "Abel Ruiz": 594234,
  "Osorio": 1297332,
  "Kamara": 601692,
  "Adam B.": 593097,
  "Adama": 593097,
  "Lookman": 38796937,
  "Januzaj": 597524,
  "Dela": 816789,
  "A. Liso": 1398226,
  "Adrián Molina": 592668,
  "Adrián": 592243,
  "A. Riquelme": 501462,
  "Aihen": 595251,
  "Aimar Blázquez": 592749,
  "Aimar": 3880727,
  "Fraga": 598089,
  "Mañas": 566369,
  "Paredes": 5487454,
  "Aitor Ruibal": 1701898,
  "Akor": 1581239,
  "Alan Matturro": 602253,
  "Alassane": 546160,
  "Albert": 593104,
  "Alberto F.": 592864,
  "A. Moleiro": 133197193,
  "A. Reina": 596013,
  "Risco": 592835,
  "Febas": 15468350,
  "A. Iturbe": 592932,
  "Mestanza": 525445,
  "Panach": 586789,
  "Rego": 593373,
  "Álex Sancris": 596837,
  "Álex Sánchez": 504527,
  "Puri?": 603879,
  "Andreev": 594366,
  "Alessio Lisci": 595128,
  "Álex Baena": 56535201,
  "Alex Costa": 592932,
  "A. Fores": 592941,
  "Lebarbier": 592122,
  "Alex Marchal": 589775,
  "Alex Moreno": 2041896,
  "Padilla": 594395,
  "A. Primo": 595528,
  "Freeman": 1249646,
  "Sorloth": 10503329,
  "Alemâo": 613079,
  "Alexis Sánchez": 1190499,
  "Alfon": 638401,
  "Pacha": 594337,
  "A. Pedraza": 1780361,
  "Nyom": 594594,
  "Arbeloa": 3208273,
  "Á. Carreras": 89409491,
  "Fidalgo": 3626674,
  "Álvaro Núñez": 15566001,
  "Odriozola": 594078,
  "Álvaro": 3715049,
  "Á. Valles": 2688751,
  "Gorosabel": 599295,
  "André Silva": 2061718,
  "Christensen": 644190,
  "Ratiu": 31848405,
  "A. Castrín": 598429,
  "Lunin": 596607,
  "A. Arcos": 566369,
  "A. Fortuño": 593297,
  "Á. Ortiz": 595155,
  "Ángel Pérez": 703748,
  "Budimir": 27414144,
  "Griezmann": 13778906,
  "Toni Lato": 593281,
  "A. Martinez": 592738,
  "Rüdiger": 14392423,
  "Salguero": 588492,
  "Antonio Sánchez": 593908,
  "A. Roca": 592649,
  "Antony": 104189335,
  "Aritz": 594352,
  "Mariezkurrena": 604001,
  "Arnau Tenas": 607125,
  "Danjuma": 10792098,
  "Zakharyan": 595585,
  "Asier Hierro": 582179,
  "A. Osambela": 592549,
  "A. Batalla": 9123124,
  "Witsel": 1558016,
  "Laporte": 7403553,
  "Ayoze": 13248693,
  "Ounahi": 5628618,
  "Diaby": 593019,
  "Santamaría": 652176
};
const MARKET_INFO = {
  "Pedri": {
    "position": "MD",
    "points": 198,
    "value": 114816160
  },
  "Remiro": {
    "position": "PT",
    "points": 181,
    "value": 4997018
  },
  "Iñaki Williams": {
    "position": "DL",
    "points": 178,
    "value": 5840963
  },
  "David Soria": {
    "position": "PT",
    "points": 176,
    "value": 5352956
  },
  "Berenguer": {
    "position": "DL",
    "points": 172,
    "value": 18600787
  },
  "Raíllo": {
    "position": "DF",
    "points": 164,
    "value": 3678098
  },
  "Sergio Herrera": {
    "position": "PT",
    "points": 161,
    "value": 10486804
  },
  "Sergio Gómez": {
    "position": "DF",
    "points": 160,
    "value": 6480668
  },
  "Courtois": {
    "position": "PT",
    "points": 157,
    "value": 51108378
  },
  "Lejeune": {
    "position": "DF",
    "points": 149,
    "value": 40779432
  },
  "Kubo": {
    "position": "MD",
    "points": 147,
    "value": 20461869
  },
  "Pau Cubarsí": {
    "position": "DF",
    "points": 142,
    "value": 45819605
  },
  "Rubén García": {
    "position": "MD",
    "points": 142,
    "value": 17021971
  },
  "Darder": {
    "position": "MD",
    "points": 141,
    "value": 12406771
  },
  "Diego López": {
    "position": "DL",
    "points": 139,
    "value": 2215499
  },
  "Álvaro García": {
    "position": "MD",
    "points": 135,
    "value": 17831775
  },
  "Rioja": {
    "position": "MD",
    "points": 135,
    "value": 9497816
  },
  "Arambarri": {
    "position": "MD",
    "points": 133,
    "value": 20759081
  },
  "Marcos Llorente": {
    "position": "DF",
    "points": 130,
    "value": 87555877
  },
  "De Frutos": {
    "position": "DL",
    "points": 129,
    "value": 41308470
  },
  "Kumbulla": {
    "position": "DF",
    "points": 127,
    "value": 596556
  },
  "Marcos Alonso": {
    "position": "DF",
    "points": 125,
    "value": 45136876
  },
  "Cardona": {
    "position": "DF",
    "points": 124,
    "value": 5161397
  },
  "Álex Balde": {
    "position": "DF",
    "points": 121,
    "value": 47120138
  },
  "Giuliano": {
    "position": "DL",
    "points": 121,
    "value": 53275470
  },
  "Boyomo": {
    "position": "DF",
    "points": 120,
    "value": 8588013
  },
  "Tchouaméni": {
    "position": "MD",
    "points": 119,
    "value": 62413764
  },
  "Valjent": {
    "position": "DF",
    "points": 115,
    "value": 2296961
  },
  "Tárrega": {
    "position": "DF",
    "points": 114,
    "value": 3400314
  },
  "Carmona": {
    "position": "DF",
    "points": 114,
    "value": 4405914
  },
  "Jofre": {
    "position": "DL",
    "points": 113,
    "value": 594056
  },
  "Comesaña": {
    "position": "MD",
    "points": 111,
    "value": 23173230
  },
  "Catena": {
    "position": "DF",
    "points": 110,
    "value": 36119042
  },
  "Guruzeta": {
    "position": "DL",
    "points": 109,
    "value": 1239495
  },
  "Parejo": {
    "position": "MD",
    "points": 106,
    "value": 876612
  },
  "Barrios": {
    "position": "MD",
    "points": 106,
    "value": 66720660
  },
  "Sow": {
    "position": "MD",
    "points": 105,
    "value": 604627
  },
  "Juan Iglesias": {
    "position": "DF",
    "points": 105,
    "value": 815907
  },
  "Jauregizar": {
    "position": "MD",
    "points": 105,
    "value": 24134275
  },
  "Torró": {
    "position": "MD",
    "points": 103,
    "value": 697946
  },
  "Hansi Flick": {
    "position": "UNK",
    "points": 101,
    "value": 612871
  },
  "Arnau": {
    "position": "DF",
    "points": 100,
    "value": 1635760
  },
  "Yuri": {
    "position": "DF",
    "points": 100,
    "value": 8030741
  },
  "Daley Blind": {
    "position": "DF",
    "points": 99,
    "value": 2632369
  },
  "Iván Martín": {
    "position": "MD",
    "points": 98,
    "value": 3134591
  },
  "Samu Costa": {
    "position": "MD",
    "points": 97,
    "value": 1319450
  },
  "Fran Beltrán": {
    "position": "MD",
    "points": 96,
    "value": 625653
  },
  "Pedrosa": {
    "position": "DF",
    "points": 95,
    "value": 594143
  },
  "David López": {
    "position": "DF",
    "points": 95,
    "value": 605301
  },
  "Javi Rodríguez": {
    "position": "DF",
    "points": 95,
    "value": 658404
  },
  "Almeida": {
    "position": "MD",
    "points": 94,
    "value": 700218
  },
  "De Galarreta": {
    "position": "MD",
    "points": 94,
    "value": 5646959
  },
  "Abel Bretones": {
    "position": "DF",
    "points": 93,
    "value": 692973
  },
  "Hugo Duro": {
    "position": "DL",
    "points": 93,
    "value": 3420567
  },
  "Chavarría": {
    "position": "DF",
    "points": 93,
    "value": 12615608
  },
  "Juanlu": {
    "position": "MD",
    "points": 93,
    "value": 701039
  },
  "Bartra": {
    "position": "DF",
    "points": 93,
    "value": 42290521
  },
  "Altimira": {
    "position": "MD",
    "points": 93,
    "value": 1008155
  },
  "Tsygankov": {
    "position": "DL",
    "points": 93,
    "value": 6742194
  },
  "Blanco": {
    "position": "MD",
    "points": 92,
    "value": 2548413
  },
  "Agirrezabala": {
    "position": "PT",
    "points": 92,
    "value": 3449846
  },
  "Sivera": {
    "position": "PT",
    "points": 90,
    "value": 2470743
  },
  "Tenaglia": {
    "position": "DF",
    "points": 89,
    "value": 11456879
  },
  "Ernesto Valverde": {
    "position": "UNK",
    "points": 88,
    "value": 598107
  },
  "Zubeldia": {
    "position": "DF",
    "points": 88,
    "value": 2712144
  },
  "Guridi": {
    "position": "MD",
    "points": 88,
    "value": 599140
  },
  "Guevara": {
    "position": "MD",
    "points": 85,
    "value": 595330
  },
  "Óscar Valentín": {
    "position": "MD",
    "points": 85,
    "value": 719975
  },
  "Prados": {
    "position": "MD",
    "points": 84,
    "value": 594620
  },
  "El Hilali": {
    "position": "DF",
    "points": 84,
    "value": 1672992
  },
  "Arda Güler": {
    "position": "MD",
    "points": 83,
    "value": 111975317
  },
  "Le Normand": {
    "position": "DF",
    "points": 83,
    "value": 7837996
  },
  "Barrenetxea": {
    "position": "MD",
    "points": 80,
    "value": 27911740
  },
  "Hugo Alvarez": {
    "position": "MD",
    "points": 80,
    "value": 621607
  },
  "Fornals": {
    "position": "MD",
    "points": 80,
    "value": 130938647
  },
  "Moncayola": {
    "position": "MD",
    "points": 78,
    "value": 5564814
  },
  "Marcelino": {
    "position": "UNK",
    "points": 76,
    "value": 598591
  },
  "Asencio": {
    "position": "DF",
    "points": 73,
    "value": 20963391
  },
  "Morlanes": {
    "position": "MD",
    "points": 72,
    "value": 602065
  },
  "Gerard": {
    "position": "DL",
    "points": 71,
    "value": 49890574
  },
  "Gayá": {
    "position": "DF",
    "points": 70,
    "value": 993144
  },
  "Jagoba Arrasate": {
    "position": "UNK",
    "points": 69,
    "value": 595961
  },
  "Unai Simón": {
    "position": "PT",
    "points": 69,
    "value": 9626213
  },
  "Claudio Giraldez": {
    "position": "UNK",
    "points": 67,
    "value": 595437
  },
  "Domingos Duarte": {
    "position": "DF",
    "points": 66,
    "value": 1087829
  },
  "Camavinga": {
    "position": "MD",
    "points": 66,
    "value": 32442886
  },
  "Fermín": {
    "position": "MD",
    "points": 65,
    "value": 146794063
  },
  "Iñigo Perez": {
    "position": "UNK",
    "points": 65,
    "value": 595341
  },
  "Mouriño": {
    "position": "DF",
    "points": 65,
    "value": 7227257
  },
  "José Bordalás": {
    "position": "UNK",
    "points": 61,
    "value": 594234
  },
  "Vesga": {
    "position": "MD",
    "points": 55,
    "value": 594128
  },
  "Pol Lozano": {
    "position": "MD",
    "points": 53,
    "value": 639605
  },
  "Moi Gómez": {
    "position": "MD",
    "points": 48,
    "value": 714990
  },
  "Turrientes": {
    "position": "MD",
    "points": 47,
    "value": 607348
  },
  "Gavi": {
    "position": "MD",
    "points": 36,
    "value": 668836
  },
  "Balliu": {
    "position": "DF",
    "points": 35,
    "value": 595528
  },
  "Cucho": {
    "position": "DL",
    "points": 33,
    "value": 60344339
  },
  "Francés": {
    "position": "DF",
    "points": 32,
    "value": 593906
  },
  "Portu": {
    "position": "DL",
    "points": 29,
    "value": 594699
  },
  "Iker Muñoz": {
    "position": "MD",
    "points": 24,
    "value": 593701
  },
  "Iván Villar": {
    "position": "PT",
    "points": 22,
    "value": 593545
  },
  "Edu Expósito": {
    "position": "MD",
    "points": 11,
    "value": 77929265
  },
  "F. Garcés": {
    "position": "DF",
    "points": 2,
    "value": 712989
  },
  "Ramón Martínez": {
    "position": "DF",
    "points": 2,
    "value": 592620
  },
  "Aitor Fdez": {
    "position": "PT",
    "points": 0,
    "value": 593795
  },
  "Yoel Lago": {
    "position": "DF",
    "points": 0,
    "value": 592905
  },
  "Aarón": {
    "position": "PT",
    "points": 0,
    "value": 21226077
  },
  "Ez Abde": {
    "position": "DL",
    "points": 0,
    "value": 55263579
  },
  "A. Rebbach": {
    "position": "DL",
    "points": 0,
    "value": 593447
  },
  "A. Abqar": {
    "position": "DF",
    "points": 0,
    "value": 695568
  },
  "Abdón": {
    "position": "DL",
    "points": 0,
    "value": 593729
  },
  "A. Mumin": {
    "position": "DF",
    "points": 0,
    "value": 593379
  },
  "Abel Ruiz": {
    "position": "DL",
    "points": 0,
    "value": 594234
  },
  "Osorio": {
    "position": "DL",
    "points": 0,
    "value": 1297332
  },
  "Kamara": {
    "position": "DL",
    "points": 0,
    "value": 601692
  },
  "Adam B.": {
    "position": "MD",
    "points": 0,
    "value": 593097
  },
  "Adama": {
    "position": "DF",
    "points": 0,
    "value": 593097
  },
  "Lookman": {
    "position": "DL",
    "points": 0,
    "value": 38796937
  },
  "Januzaj": {
    "position": "MD",
    "points": 0,
    "value": 597524
  },
  "Dela": {
    "position": "DF",
    "points": 0,
    "value": 816789
  },
  "A. Liso": {
    "position": "DL",
    "points": 0,
    "value": 1398226
  },
  "Adrián Molina": {
    "position": "PT",
    "points": 0,
    "value": 592668
  },
  "Adrián": {
    "position": "DL",
    "points": 0,
    "value": 592243
  },
  "A. Riquelme": {
    "position": "MD",
    "points": 0,
    "value": 501462
  },
  "Aihen": {
    "position": "DF",
    "points": 0,
    "value": 595251
  },
  "Aimar Blázquez": {
    "position": "DL",
    "points": 0,
    "value": 592749
  },
  "Aimar": {
    "position": "MD",
    "points": 0,
    "value": 3880727
  },
  "Fraga": {
    "position": "PT",
    "points": 0,
    "value": 598089
  },
  "Mañas": {
    "position": "DL",
    "points": 0,
    "value": 566369
  },
  "Paredes": {
    "position": "DF",
    "points": 0,
    "value": 5487454
  },
  "Aitor Ruibal": {
    "position": "DL",
    "points": 0,
    "value": 1701898
  },
  "Akor": {
    "position": "DL",
    "points": 0,
    "value": 1581239
  },
  "Alan Matturro": {
    "position": "DF",
    "points": 0,
    "value": 602253
  },
  "Alassane": {
    "position": "MD",
    "points": 0,
    "value": 546160
  },
  "Albert": {
    "position": "DF",
    "points": 0,
    "value": 593104
  },
  "Alberto F.": {
    "position": "PT",
    "points": 0,
    "value": 592864
  },
  "A. Moleiro": {
    "position": "MD",
    "points": 0,
    "value": 133197193
  },
  "A. Reina": {
    "position": "MD",
    "points": 0,
    "value": 596013
  },
  "Risco": {
    "position": "MD",
    "points": 0,
    "value": 592835
  },
  "Febas": {
    "position": "MD",
    "points": 0,
    "value": 15468350
  },
  "A. Iturbe": {
    "position": "PT",
    "points": 0,
    "value": 592932
  },
  "Mestanza": {
    "position": "MD",
    "points": 0,
    "value": 525445
  },
  "Panach": {
    "position": "DF",
    "points": 0,
    "value": 586789
  },
  "Rego": {
    "position": "DF",
    "points": 0,
    "value": 593373
  },
  "Álex Sancris": {
    "position": "DL",
    "points": 0,
    "value": 596837
  },
  "Álex Sánchez": {
    "position": "MD",
    "points": 0,
    "value": 504527
  },
  "Puri?": {
    "position": "DF",
    "points": 0,
    "value": 603879
  },
  "Andreev": {
    "position": "PT",
    "points": 0,
    "value": 594366
  },
  "Alessio Lisci": {
    "position": "UNK",
    "points": 0,
    "value": 595128
  },
  "Álex Baena": {
    "position": "MD",
    "points": 0,
    "value": 56535201
  },
  "Alex Costa": {
    "position": "DL",
    "points": 0,
    "value": 592932
  },
  "A. Fores": {
    "position": "DL",
    "points": 0,
    "value": 592941
  },
  "Lebarbier": {
    "position": "DF",
    "points": 0,
    "value": 592122
  },
  "Alex Marchal": {
    "position": "MD",
    "points": 0,
    "value": 589775
  },
  "Alex Moreno": {
    "position": "DF",
    "points": 0,
    "value": 2041896
  },
  "Padilla": {
    "position": "PT",
    "points": 0,
    "value": 594395
  },
  "A. Primo": {
    "position": "PT",
    "points": 0,
    "value": 595528
  },
  "Freeman": {
    "position": "DF",
    "points": 0,
    "value": 1249646
  },
  "Sorloth": {
    "position": "DL",
    "points": 0,
    "value": 10503329
  },
  "Alemâo": {
    "position": "DL",
    "points": 0,
    "value": 613079
  },
  "Alexis Sánchez": {
    "position": "DL",
    "points": 0,
    "value": 1190499
  },
  "Alfon": {
    "position": "DL",
    "points": 0,
    "value": 638401
  },
  "Pacha": {
    "position": "DF",
    "points": 0,
    "value": 594337
  },
  "A. Pedraza": {
    "position": "DF",
    "points": 0,
    "value": 1780361
  },
  "Nyom": {
    "position": "DF",
    "points": 0,
    "value": 594594
  },
  "Arbeloa": {
    "position": "UNK",
    "points": 0,
    "value": 3208273
  },
  "Á. Carreras": {
    "position": "DF",
    "points": 0,
    "value": 89409491
  },
  "Fidalgo": {
    "position": "MD",
    "points": 0,
    "value": 3626674
  },
  "Álvaro Núñez": {
    "position": "DF",
    "points": 0,
    "value": 15566001
  },
  "Odriozola": {
    "position": "DF",
    "points": 0,
    "value": 594078
  },
  "Álvaro": {
    "position": "DL",
    "points": 0,
    "value": 3715049
  },
  "Á. Valles": {
    "position": "PT",
    "points": 0,
    "value": 2688751
  },
  "Gorosabel": {
    "position": "DF",
    "points": 0,
    "value": 599295
  },
  "André Silva": {
    "position": "DL",
    "points": 0,
    "value": 2061718
  },
  "Christensen": {
    "position": "DF",
    "points": 0,
    "value": 644190
  },
  "Ratiu": {
    "position": "DF",
    "points": 0,
    "value": 31848405
  },
  "A. Castrín": {
    "position": "DF",
    "points": 0,
    "value": 598429
  },
  "Lunin": {
    "position": "PT",
    "points": 0,
    "value": 596607
  },
  "A. Arcos": {
    "position": "MD",
    "points": 0,
    "value": 566369
  },
  "A. Fortuño": {
    "position": "PT",
    "points": 0,
    "value": 593297
  },
  "Á. Ortiz": {
    "position": "DF",
    "points": 0,
    "value": 595155
  },
  "Ángel Pérez": {
    "position": "DL",
    "points": 0,
    "value": 703748
  },
  "Budimir": {
    "position": "DL",
    "points": 0,
    "value": 27414144
  },
  "Griezmann": {
    "position": "DL",
    "points": 0,
    "value": 13778906
  },
  "Toni Lato": {
    "position": "DF",
    "points": 0,
    "value": 593281
  },
  "A. Martinez": {
    "position": "MD",
    "points": 0,
    "value": 592738
  },
  "Rüdiger": {
    "position": "DF",
    "points": 0,
    "value": 14392423
  },
  "Salguero": {
    "position": "DF",
    "points": 0,
    "value": 588492
  },
  "Antonio Sánchez": {
    "position": "MD",
    "points": 0,
    "value": 593908
  },
  "A. Roca": {
    "position": "MD",
    "points": 0,
    "value": 592649
  },
  "Antony": {
    "position": "DL",
    "points": 0,
    "value": 104189335
  },
  "Aritz": {
    "position": "DF",
    "points": 0,
    "value": 594352
  },
  "Mariezkurrena": {
    "position": "DL",
    "points": 0,
    "value": 604001
  },
  "Arnau Tenas": {
    "position": "PT",
    "points": 0,
    "value": 607125
  },
  "Danjuma": {
    "position": "DL",
    "points": 0,
    "value": 10792098
  },
  "Zakharyan": {
    "position": "MD",
    "points": 0,
    "value": 595585
  },
  "Asier Hierro": {
    "position": "DL",
    "points": 0,
    "value": 582179
  },
  "A. Osambela": {
    "position": "MD",
    "points": 0,
    "value": 592549
  },
  "A. Batalla": {
    "position": "PT",
    "points": 0,
    "value": 9123124
  },
  "Witsel": {
    "position": "MD",
    "points": 0,
    "value": 1558016
  },
  "Laporte": {
    "position": "DF",
    "points": 0,
    "value": 7403553
  },
  "Ayoze": {
    "position": "DL",
    "points": 0,
    "value": 13248693
  },
  "Ounahi": {
    "position": "MD",
    "points": 0,
    "value": 5628618
  },
  "Diaby": {
    "position": "DF",
    "points": 0,
    "value": 593019
  },
  "Santamaría": {
    "position": "MD",
    "points": 0,
    "value": 652176
  }
};
const MARKET_TRENDS = {
  "Pedri": {
    "trend": -1639700,
    "trendPct": -1.41
  },
  "Remiro": {
    "trend": 4726,
    "trendPct": 0.09
  },
  "Iñaki Williams": {
    "trend": -4916,
    "trendPct": -0.08
  },
  "David Soria": {
    "trend": -81972,
    "trendPct": -1.51
  },
  "Berenguer": {
    "trend": -267535,
    "trendPct": -1.42
  },
  "Raíllo": {
    "trend": -72143,
    "trendPct": -1.92
  },
  "Sergio Herrera": {
    "trend": -144038,
    "trendPct": -1.35
  },
  "Sergio Gómez": {
    "trend": 66599,
    "trendPct": 1.04
  },
  "Courtois": {
    "trend": -216435,
    "trendPct": -0.42
  },
  "Lejeune": {
    "trend": -33510,
    "trendPct": -0.08
  },
  "Kubo": {
    "trend": -497186,
    "trendPct": -2.37
  },
  "Pau Cubarsí": {
    "trend": -35223,
    "trendPct": -0.08
  },
  "Rubén García": {
    "trend": 183330,
    "trendPct": 1.09
  },
  "Darder": {
    "trend": 138011,
    "trendPct": 1.12
  },
  "Diego López": {
    "trend": -53211,
    "trendPct": -2.35
  },
  "Álvaro García": {
    "trend": 107518,
    "trendPct": 0.61
  },
  "Rioja": {
    "trend": 123857,
    "trendPct": 1.32
  },
  "Arambarri": {
    "trend": -18594,
    "trendPct": -0.09
  },
  "Marcos Llorente": {
    "trend": -74162,
    "trendPct": -0.08
  },
  "De Frutos": {
    "trend": 585284,
    "trendPct": 1.44
  },
  "Kumbulla": {
    "trend": 2528,
    "trendPct": 0.43
  },
  "Marcos Alonso": {
    "trend": 551246,
    "trendPct": 1.24
  },
  "Cardona": {
    "trend": -108994,
    "trendPct": -2.07
  },
  "Álex Balde": {
    "trend": 200889,
    "trendPct": 0.43
  },
  "Giuliano": {
    "trend": -131615,
    "trendPct": -0.25
  },
  "Boyomo": {
    "trend": -177086,
    "trendPct": -2.02
  },
  "Tchouaméni": {
    "trend": 488035,
    "trendPct": 0.79
  },
  "Valjent": {
    "trend": -28946,
    "trendPct": -1.24
  },
  "Tárrega": {
    "trend": -69287,
    "trendPct": -2.0
  },
  "Carmona": {
    "trend": -99278,
    "trendPct": -2.2
  },
  "Jofre": {
    "trend": 2632,
    "trendPct": 0.45
  },
  "Comesaña": {
    "trend": -461726,
    "trendPct": -1.95
  },
  "Catena": {
    "trend": 36937,
    "trendPct": 0.1
  },
  "Guruzeta": {
    "trend": -11370,
    "trendPct": -0.91
  },
  "Parejo": {
    "trend": -3546,
    "trendPct": -0.4
  },
  "Barrios": {
    "trend": -1734644,
    "trendPct": -2.53
  },
  "Sow": {
    "trend": 2192,
    "trendPct": 0.36
  },
  "Juan Iglesias": {
    "trend": -3040,
    "trendPct": -0.37
  },
  "Jauregizar": {
    "trend": -15340,
    "trendPct": -0.06
  },
  "Torró": {
    "trend": 3371,
    "trendPct": 0.49
  },
  "Hansi Flick": {
    "trend": 1848,
    "trendPct": 0.3
  },
  "Arnau": {
    "trend": 20862,
    "trendPct": 1.29
  },
  "Yuri": {
    "trend": -16452,
    "trendPct": -0.2
  },
  "Daley Blind": {
    "trend": 43050,
    "trendPct": 1.66
  },
  "Iván Martín": {
    "trend": 20145,
    "trendPct": 0.65
  },
  "Samu Costa": {
    "trend": -9649,
    "trendPct": -0.73
  },
  "Fran Beltrán": {
    "trend": 1316,
    "trendPct": 0.21
  },
  "Pedrosa": {
    "trend": 2629,
    "trendPct": 0.44
  },
  "David López": {
    "trend": 2164,
    "trendPct": 0.36
  },
  "Javi Rodríguez": {
    "trend": -49,
    "trendPct": -0.01
  },
  "Almeida": {
    "trend": -1791,
    "trendPct": -0.26
  },
  "De Galarreta": {
    "trend": -21754,
    "trendPct": -0.38
  },
  "Abel Bretones": {
    "trend": -1489,
    "trendPct": -0.21
  },
  "Hugo Duro": {
    "trend": -46083,
    "trendPct": -1.33
  },
  "Chavarría": {
    "trend": -273893,
    "trendPct": -2.12
  },
  "Juanlu": {
    "trend": -1825,
    "trendPct": -0.26
  },
  "Bartra": {
    "trend": -198144,
    "trendPct": -0.47
  },
  "Altimira": {
    "trend": -14622,
    "trendPct": -1.43
  },
  "Tsygankov": {
    "trend": -83616,
    "trendPct": -1.22
  },
  "Blanco": {
    "trend": -2012,
    "trendPct": -0.08
  },
  "Agirrezabala": {
    "trend": -91131,
    "trendPct": -2.57
  },
  "Sivera": {
    "trend": -34488,
    "trendPct": -1.38
  },
  "Tenaglia": {
    "trend": -127023,
    "trendPct": -1.1
  },
  "Ernesto Valverde": {
    "trend": 2463,
    "trendPct": 0.41
  },
  "Zubeldia": {
    "trend": -35373,
    "trendPct": -1.29
  },
  "Guridi": {
    "trend": 2420,
    "trendPct": 0.41
  },
  "Guevara": {
    "trend": 2579,
    "trendPct": 0.44
  },
  "Óscar Valentín": {
    "trend": -2614,
    "trendPct": -0.36
  },
  "Prados": {
    "trend": 2609,
    "trendPct": 0.44
  },
  "El Hilali": {
    "trend": -36810,
    "trendPct": -2.15
  },
  "Arda Güler": {
    "trend": 1749856,
    "trendPct": 1.59
  },
  "Le Normand": {
    "trend": -6759,
    "trendPct": -0.09
  },
  "Barrenetxea": {
    "trend": -717835,
    "trendPct": -2.51
  },
  "Hugo Alvarez": {
    "trend": 1484,
    "trendPct": 0.24
  },
  "Fornals": {
    "trend": 534630,
    "trendPct": 0.41
  },
  "Moncayola": {
    "trend": -109566,
    "trendPct": -1.93
  },
  "Marcelino": {
    "trend": 2443,
    "trendPct": 0.41
  },
  "Asencio": {
    "trend": 406069,
    "trendPct": 1.98
  },
  "Morlanes": {
    "trend": 2299,
    "trendPct": 0.38
  },
  "Gerard": {
    "trend": 971137,
    "trendPct": 1.99
  },
  "Gayá": {
    "trend": -13996,
    "trendPct": -1.39
  },
  "Jagoba Arrasate": {
    "trend": 2553,
    "trendPct": 0.43
  },
  "Unai Simón": {
    "trend": -82431,
    "trendPct": -0.85
  },
  "Claudio Giraldez": {
    "trend": 2575,
    "trendPct": 0.43
  },
  "Domingos Duarte": {
    "trend": -9466,
    "trendPct": -0.86
  },
  "Camavinga": {
    "trend": 761684,
    "trendPct": 2.4
  },
  "Fermín": {
    "trend": 1730231,
    "trendPct": 1.19
  },
  "Iñigo Perez": {
    "trend": 2579,
    "trendPct": 0.44
  },
  "Mouriño": {
    "trend": -114586,
    "trendPct": -1.56
  },
  "José Bordalás": {
    "trend": 2625,
    "trendPct": 0.44
  },
  "Vesga": {
    "trend": 2629,
    "trendPct": 0.44
  },
  "Pol Lozano": {
    "trend": 734,
    "trendPct": 0.11
  },
  "Moi Gómez": {
    "trend": -2407,
    "trendPct": -0.34
  },
  "Turrientes": {
    "trend": 2078,
    "trendPct": 0.34
  },
  "Gavi": {
    "trend": -484,
    "trendPct": -0.07
  },
  "Balliu": {
    "trend": 2571,
    "trendPct": 0.43
  },
  "Cucho": {
    "trend": -715218,
    "trendPct": -1.17
  },
  "Francés": {
    "trend": 2639,
    "trendPct": 0.45
  },
  "Portu": {
    "trend": 2605,
    "trendPct": 0.44
  },
  "Iker Muñoz": {
    "trend": 2647,
    "trendPct": 0.45
  },
  "Iván Villar": {
    "trend": 2654,
    "trendPct": 0.45
  },
  "Edu Expósito": {
    "trend": 780006,
    "trendPct": 1.01
  },
  "F. Garcés": {
    "trend": 4426,
    "trendPct": 0.62
  },
  "Ramón Martínez": {
    "trend": 2692,
    "trendPct": 0.46
  },
  "Aitor Fdez": {
    "trend": 2643,
    "trendPct": 0.45
  },
  "Yoel Lago": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Aarón": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Ez Abde": {
    "trend": 0,
    "trendPct": 0.0
  },
  "A. Rebbach": {
    "trend": 0,
    "trendPct": 0.0
  },
  "A. Abqar": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Abdón": {
    "trend": 0,
    "trendPct": 0.0
  },
  "A. Mumin": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Abel Ruiz": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Osorio": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Kamara": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Adam B.": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Adama": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Lookman": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Januzaj": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Dela": {
    "trend": 0,
    "trendPct": 0.0
  },
  "A. Liso": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Adrián Molina": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Adrián": {
    "trend": 0,
    "trendPct": 0.0
  },
  "A. Riquelme": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Aihen": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Aimar Blázquez": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Aimar": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Fraga": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Mañas": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Paredes": {
    "trend": -87354,
    "trendPct": -1.57
  },
  "Aitor Ruibal": {
    "trend": -9381,
    "trendPct": -0.55
  },
  "Akor": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Alan Matturro": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Alassane": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Albert": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Alberto F.": {
    "trend": 0,
    "trendPct": 0.0
  },
  "A. Moleiro": {
    "trend": 921486,
    "trendPct": 0.7
  },
  "A. Reina": {
    "trend": 2551,
    "trendPct": 0.43
  },
  "Risco": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Febas": {
    "trend": 213758,
    "trendPct": 1.4
  },
  "A. Iturbe": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Mestanza": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Panach": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Rego": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Álex Sancris": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Álex Sánchez": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Puri?": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Andreev": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Alessio Lisci": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Álex Baena": {
    "trend": -290981,
    "trendPct": -0.51
  },
  "Alex Costa": {
    "trend": 0,
    "trendPct": 0.0
  },
  "A. Fores": {
    "trend": 2679,
    "trendPct": 0.45
  },
  "Lebarbier": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Alex Marchal": {
    "trend": 0,
    "trendPct": 0.0
  },
  "Alex Moreno": {
    "trend": -47640,
    "trendPct": -2.28
  },
  "Padilla": {
    "trend": 2618,
    "trendPct": 0.44
  },
  "A. Primo": {
    "trend": 2571,
    "trendPct": 0.43
  },
  "Freeman": {
    "trend": -24684,
    "trendPct": -1.94
  },
  "Sorloth": {
    "trend": -128938,
    "trendPct": -1.21
  },
  "Alemâo": {
    "trend": 1840,
    "trendPct": 0.3
  },
  "Alexis Sánchez": {
    "trend": -22219,
    "trendPct": -1.83
  },
  "Alfon": {
    "trend": 785,
    "trendPct": 0.12
  },
  "Pacha": {
    "trend": 2621,
    "trendPct": 0.44
  },
  "A. Pedraza": {
    "trend": -36298,
    "trendPct": -2.0
  },
  "Nyom": {
    "trend": 2610,
    "trendPct": 0.44
  },
  "Arbeloa": {
    "trend": -106293,
    "trendPct": -3.21
  },
  "Á. Carreras": {
    "trend": -1093751,
    "trendPct": -1.21
  },
  "Fidalgo": {
    "trend": -50897,
    "trendPct": -1.38
  },
  "Álvaro Núñez": {
    "trend": -375648,
    "trendPct": -2.36
  },
  "Odriozola": {
    "trend": 2631,
    "trendPct": 0.44
  },
  "Álvaro": {
    "trend": 47800,
    "trendPct": 1.3
  },
  "Á. Valles": {
    "trend": -21895,
    "trendPct": -0.81
  },
  "Gorosabel": {
    "trend": 2414,
    "trendPct": 0.4
  },
  "André Silva": {
    "trend": -43966,
    "trendPct": -2.09
  },
  "Christensen": {
    "trend": 543,
    "trendPct": 0.08
  },
  "Ratiu": {
    "trend": 266997,
    "trendPct": 0.85
  },
  "A. Castrín": {
    "trend": 2450,
    "trendPct": 0.41
  },
  "Lunin": {
    "trend": 2526,
    "trendPct": 0.43
  },
  "A. Arcos": {
    "trend": 3786,
    "trendPct": 0.67
  },
  "A. Fortuño": {
    "trend": 2664,
    "trendPct": 0.45
  },
  "Á. Ortiz": {
    "trend": 2586,
    "trendPct": 0.44
  },
  "Ángel Pérez": {
    "trend": -1938,
    "trendPct": -0.27
  },
  "Budimir": {
    "trend": 590248,
    "trendPct": 2.2
  },
  "Griezmann": {
    "trend": -174290,
    "trendPct": -1.25
  },
  "Toni Lato": {
    "trend": 2665,
    "trendPct": 0.45
  },
  "A. Martinez": {
    "trend": 2687,
    "trendPct": 0.46
  },
  "Rüdiger": {
    "trend": -173079,
    "trendPct": -1.19
  },
  "Salguero": {
    "trend": 2864,
    "trendPct": 0.49
  },
  "Antonio Sánchez": {
    "trend": 2638,
    "trendPct": 0.45
  },
  "A. Roca": {
    "trend": 2691,
    "trendPct": 0.46
  },
  "Antony": {
    "trend": -768515,
    "trendPct": -0.73
  },
  "Aritz": {
    "trend": 2620,
    "trendPct": 0.44
  },
  "Mariezkurrena": {
    "trend": 2218,
    "trendPct": 0.37
  },
  "Arnau Tenas": {
    "trend": 2088,
    "trendPct": 0.35
  },
  "Danjuma": {
    "trend": 103573,
    "trendPct": 0.97
  },
  "Zakharyan": {
    "trend": 2569,
    "trendPct": 0.43
  },
  "Asier Hierro": {
    "trend": 3127,
    "trendPct": 0.54
  },
  "A. Osambela": {
    "trend": 2695,
    "trendPct": 0.46
  },
  "A. Batalla": {
    "trend": -157670,
    "trendPct": -1.7
  },
  "Witsel": {
    "trend": -35314,
    "trendPct": -2.22
  },
  "Laporte": {
    "trend": -37278,
    "trendPct": -0.5
  },
  "Ayoze": {
    "trend": -299663,
    "trendPct": -2.21
  },
  "Ounahi": {
    "trend": -118873,
    "trendPct": -2.07
  },
  "Diaby": {
    "trend": 2676,
    "trendPct": 0.45
  },
  "Santamaría": {
    "trend": 211,
    "trendPct": 0.03
  }
};
