import glob
import requests
from bs4 import BeautifulSoup
import json
import datetime
import os

# Configuration
URL = "https://www.guiafantasy.com/jugadores"
OUTPUT_FILE = "market_data.js"

def parse_money(text):
    """Parses '123.456€' to integer 123456"""
    if not text: return 0
    clean = text.replace('.', '').replace('€', '').strip()
    try:
        return int(clean)
    except:
        return 0

def scrape_market():
    print("🚀 Starting Market Scraper (Multi-File Mode)...")
    
    all_players = []
    
    # 1. Scan for all HTML files in the current directory
    html_files = glob.glob("*.html")
    print(f"Found {len(html_files)} HTML files. Scanning for player data...")
    
    processed_files = 0
    
    for filename in html_files:
        # Skip critical project files
        if filename in ["index.html", "plantilla_caratula.html", "dashboard.html"]: continue
        
        try:
            with open(filename, "r", encoding="utf-8") as f:
                content = f.read()
                
            # Crucial check: Does this file actually contain fantasy players?
            if "ficha_jugador" in content:
                print(f"Processing '{filename}'...")
                soup = BeautifulSoup(content, 'html.parser')
                cards = soup.find_all('div', class_='ficha_jugador')
                
                if len(cards) > 0:
                     all_players.extend(cards)
                     processed_files += 1
                     print(f"  -> +{len(cards)} players found (Total: {len(all_players)})")
            else:
                if filename not in ["index.html"]:
                    print(f"Skipping '{filename}' (No player cards found)")
                    
        except Exception as e:
            print(f"Error reading {filename}: {e}")

    # 2. Convert to Soup objects list for processing
    player_cards = all_players
    
    if not player_cards:
        print("❌ No players found in any local HTML file.")
        print("👉 Please save the Guia Fantasy pages as .html files in this folder.")
        return

    print(f"\n✅ Total unique cards found: {len(player_cards)}. Parsing details...")
    
    market_data = {}   # Name -> Value
    market_info = {}   # Name -> {position, points, value}
    market_trends = {} # Name -> {trend, trendPct}
    
    for card in player_cards:
        try:
            # Name
            name_tag = card.find('span', class_='titulo_ficha_jugador')
            if not name_tag: continue
            name = name_tag.get_text(strip=True)
            
            # Normalize names
            if name == "Williams Arthuer": name = "Iñaki Williams"
            
            # Value
            val_tag = card.find('small')
            value = parse_money(val_tag.get_text(strip=True)) if val_tag else 0
            
            # Points
            points = 0
            points_tag = card.find('span', class_='label-primary')
            if points_tag:
                 try:
                     points = int(points_tag.get_text(strip=True))
                 except:
                     points = 0
            
            # Position
            pos = "MD" # default
            pos_tags = card.find_all('span', class_='label-posicion')
            for tag in pos_tags:
                txt = tag.get_text(strip=True)
                if txt in ['PT', 'DF', 'MD', 'DL']:
                    pos = txt
                    break
            
            # Trend
            trend_val = 0
            trend_div = card.find('div', class_='success') or card.find('div', class_='danger')
            
            if trend_div:
                trend_text = trend_div.get_text(strip=True)
                trend_val = parse_money(trend_text)
                if 'danger' in trend_div.get('class', []):
                    trend_val = -trend_val
            
            # Trend Pct
            trend_pct = 0
            if value > 0:
                prev_val = value - trend_val
                if prev_val != 0:
                    trend_pct = (trend_val / prev_val) * 100

            market_data[name] = value
            market_info[name] = { "position": pos, "points": points, "value": value }
            market_trends[name] = { "trend": trend_val, "trendPct": round(trend_pct, 2) }
            
        except Exception as e:
            continue

    # Write JS file
    current_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    
    js_content = f"""// Auto-generated by scrape_market.py from local HTML files
// Generated: {current_time}
// Total Players: {len(market_data)}
const MARKET_DATA = {json.dumps(market_data, indent=2, ensure_ascii=False)};
const MARKET_INFO = {json.dumps(market_info, indent=2, ensure_ascii=False)};
const MARKET_TRENDS = {json.dumps(market_trends, indent=2, ensure_ascii=False)};
"""
    
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(js_content)
        
    print(f"💾 market_data.js saved successfully with {len(market_data)} players!")


if __name__ == "__main__":
    scrape_market()
